# -*- coding: utf-8 -*-
"""
build_unit1_batch3.py
Builds full 20-25 minute broadcast tiki-taka scripts for Lectures 11, 12, 13, 14, and 15.
Target: 2,280 - 2,550 words per lecture.
"""
import json

L11_TEXT = {
    1: (
        "Prof. Park: Welcome everyone to Lecture 11 of M090 Introductory Algebra! I am Professor Eunju Park, and joining me at the teaching desk is TA Sora. "
        "Today, we cross a major milestone in our course: we begin Section 1.6 on workbook pages 18 and 19: Solving Linear Equations and the Properties of Equality.\n"
        "TA Sora: Hello everyone! Up until today, we have been working with algebraic expressions—simplifying them, adding them, and multiplying them. "
        "Notice that an expression has NO equal sign! You cannot solve an expression; you can only simplify it. "
        "Today, for the first time, we encounter an EQUATION: two algebraic expressions joined by an equal sign! "
        "An equation is a complete mathematical sentence that states: 'The left side has the EXACT same numerical value as the right side!'\n"
        "Prof. Park: That distinction is foundational. Think of an equation as a traditional mechanical balance scale, like the antique gold and grain scales used during the Montana gold rush in Virginia City and Alder Gulch. "
        "If you have equal weights on both pans, the scale balances perfectly horizontally. "
        "If you add 5 pounds to the left pan, the scale tips—unless you immediately add the exact same 5 pounds to the right pan! "
        "That gives us our Golden Rule of Equation Solving: Whatever you do to one side of the equation, you MUST do to the other side!\n"
        "TA Sora: That is the universal law of algebra! Let's state our two core properties: "
        "1. Addition and Subtraction Property of Equality: If a = b, then a + c = b + c, and a - c = b - c. "
        "Adding or subtracting the exact same number from both sides maintains complete equality. "
        "2. Multiplication and Division Property of Equality: If a = b and c is not zero, then a · c = b · c, and a / c = b / c. "
        "Multiplying or dividing both sides by the exact same non-zero number maintains complete equality.\n"
        "Prof. Park: And what is our ultimate goal when solving an equation? "
        "Our goal is to isolate the variable completely by itself on one side: x = [a number]. "
        "To isolate the variable, we undo the operations that are attached to it using INVERSE operations in reverse order: "
        "Undo addition with subtraction; undo subtraction with addition; undo multiplication with division; and undo division with multiplication. "
        "Let's put this into practice on slide 2 with our first two-step equation!"
    ),
    2: (
        "Prof. Park: On slide 2, let's examine Section 1.6 Example 1A on workbook page 18: "
        "Solve the linear equation for the given variable: 3x - 8 = -12.\n"
        "TA Sora: Look at the variable x on the left side. What is happening to x? "
        "Two operations are attached to x: "
        "First, x is multiplied by 3. "
        "Second, 8 is subtracted from that result. "
        "When solving equations, we undo operations in REVERSE order of operations—reverse PEMDAS! "
        "Think of getting dressed in the morning: you put your socks on first, then your boots. "
        "When taking them off at night, what comes off first? The boots! "
        "So we undo the addition or subtraction first, and save the multiplication or division for the very last step!\n"
        "Prof. Park: What a brilliant analogy, Sora! Let's take off the boots first: "
        "To undo the subtraction of 8, we add 8 to BOTH sides of the equation: "
        "3x - 8 + 8 = -12 + 8. "
        "On the left side: -8 + 8 = 0, leaving just 3x. "
        "On the right side: -12 + 8 = -4! "
        "So our equation simplifies to: 3x = -4.\n"
        "TA Sora: Now take off the socks: x is multiplied by 3. "
        "The inverse of multiplying by 3 is dividing by 3! "
        "Divide BOTH sides by 3: "
        "(3x) / 3 = (-4) / 3. "
        "3 / 3 is 1, leaving x isolated: x = -4/3! "
        "Notice that our answer is an improper fraction in simplest form. "
        "Do NOT convert it to a decimal like -1.333 unless the problem explicitly asks for a decimal. "
        "In algebra, -4/3 is exact, elegant, and standard.\n"
        "Prof. Park: Now let's perform our mandatory check: plug x = -4/3 back into the original equation: "
        "3(-4/3) - 8 = -4 - 8 = -12. "
        "-12 = -12 is a true statement! "
        "That proves with 100% mathematical certainty that x = -4/3 is the correct unique solution!"
    ),
    3: (
        "Prof. Park: Slide 3 introduces the notorious 'Negative Coefficient Trap': "
        "Section 1.6 Example 1B on workbook page 18: "
        "Solve: 6 - 4w = 15.\n"
        "TA Sora: Danger alert! Look at the left side: 6 - 4w. "
        "Students see the minus sign after 6 and mistakenly think the 6 is negative! "
        "They say: 'I should add 6 to both sides.' "
        "That is completely wrong! The number 6 has an invisible positive sign in front of it: +6! "
        "The minus sign belongs to the term 4w! "
        "So the coefficient of w is NEGATIVE 4!\n"
        "Prof. Park: That is one of the most common errors in all of introductory algebra. "
        "To eliminate the constant +6, we must SUBTRACT 6 from both sides: "
        "6 - 4w - 6 = 15 - 6. "
        "On the left: 6 - 6 = 0, leaving -4w! "
        "Notice the minus sign did NOT disappear—it stays attached to 4w! "
        "On the right: 15 - 6 = 9. "
        "So our equation is: -4w = 9.\n"
        "TA Sora: Now to isolate w, we must divide both sides by the ENTIRE coefficient of w, which is -4! "
        "Divide both sides by -4: "
        "(-4w) / (-4) = 9 / (-4). "
        "Negative divided by negative is positive: w = -9/4! "
        "If a student had forgotten that the 4 was negative, they would have divided by +4 and gotten +9/4, losing points. "
        "Always circle the sign in front of the coefficient to remind yourself that the sign travels with the number!\n"
        "Prof. Park: Let's check w = -9/4: "
        "6 - 4(-9/4) = 6 - (-9) = 6 + 9 = 15. "
        "15 = 15! It checks out perfectly. Always guard your signs!"
    ),
    4: (
        "Prof. Park: On slide 4, we examine Section 1.6 Examples 1C and 1D on workbook page 18: "
        "Equations where you must combine like terms on the same side BEFORE moving across the equal sign!\n"
        "TA Sora: Here is another vital distinction: "
        "If two like terms are on the SAME side of the equal sign, you do NOT use inverse operations! "
        "You simply combine them using regular addition and subtraction from Section 1.3! "
        "You only use inverse operations when moving a term ACROSS the equal sign to the other side!\n"
        "Prof. Park: Let's solve Example 1C: y + 4 + 5y - 9 = 87. "
        "Look at the left side: we have y and +5y. They are like terms! y + 5y = 6y. "
        "We also have constants +4 and -9: 4 - 9 = -5. "
        "So the left side simplifies to: 6y - 5 = 87.\n"
        "TA Sora: Look how simple that is now! It's just a standard two-step equation: "
        "Add 5 to both sides: 6y = 87 + 5 = 92. "
        "Divide both sides by 6: y = 92/6. "
        "Both 92 and 6 are even numbers, so divide top and bottom by 2: "
        "y = 46/3! That is our simplified solution.\n"
        "Prof. Park: Now let's solve Example 1D: 6r - 3r + 94 + 2r = 18. "
        "Combine all r terms on the left side: 6r - 3r = 3r, and 3r + 2r = 5r! "
        "So the left side becomes: 5r + 94 = 18. "
        "Subtract 94 from both sides: "
        "5r = 18 - 94 = -76. "
        "Divide both sides by 5: r = -76/5! "
        "76 is not divisible by 5, so -76/5 is our final irreducible answer. "
        "Combining like terms first cuts the complexity of an equation in half before you ever touch an inverse operation!"
    ),
    5: (
        "Prof. Park: Slide 5 concludes Lecture 11 with Section 1.6 Examples 2A and 2B on workbook page 18: "
        "Solving Equations involving the Distributive Property.\n"
        "TA Sora: When an equation contains parentheses, our first priority is to eliminate parentheses using the Distributive Property. "
        "Let's look at Example 2A: 10(a - 5) + 2 = -3. "
        "Step 1: Distribute 10 across (a - 5): "
        "10 · a - 10 · 5 = 10a - 50. "
        "So our equation is: 10a - 50 + 2 = -3. "
        "Step 2: Combine like terms on the left side: -50 + 2 = -48. "
        "So we have: 10a - 48 = -3. "
        "Step 3: Add 48 to both sides: 10a = -3 + 48 = 45. "
        "Step 4: Divide both sides by 10: a = 45/10. "
        "Reduce by dividing top and bottom by 5: a = 9/2!\n"
        "Prof. Park: Outstanding! Now let's tackle Example 2B, which has variables on BOTH sides of the equation: "
        "6(x - 2) - 8 = 3x - 20.\n"
        "TA Sora: Step 1: Distribute the 6 on the left: 6x - 12 - 8 = 3x - 20. "
        "Step 2: Combine like terms on the left: -12 - 8 = -20. "
        "So we get: 6x - 20 = 3x - 20. "
        "Step 3: Move variable terms to one side. Subtract 3x from both sides: "
        "6x - 3x - 20 = -20, which gives: 3x - 20 = -20. "
        "Step 4: Add 20 to both sides: 3x = -20 + 20 = 0! "
        "Step 5: Divide both sides by 3: x = 0 / 3 = 0!\n"
        "Prof. Park: Students often freeze when they see zero and think something went wrong. "
        "Zero is a perfectly valid, real number! If x = 0, let's check: "
        "Left: 6(0 - 2) - 8 = 6(-2) - 8 = -12 - 8 = -20. "
        "Right: 3(0) - 20 = 0 - 20 = -20. "
        "-20 = -20! It checks completely. The solution is x = 0! "
        "In Lecture 12, we will look at equations where variables cancel out completely—identities and contradictions. "
        "Great job today, and we look forward to seeing you in Lecture 12!"
    )
}

L12_TEXT = {
    1: (
        "Prof. Park: Welcome everyone to Lecture 12 of M090 Introductory Algebra! I am Professor Eunju Park, and joining me at the teaching desk is TA Sora. "
        "Today, we explore Section 1.6 Part 2 on workbook page 19: Classifying Linear Equations—Conditional Equations, Contradictions, and Identities.\n"
        "TA Sora: Hello everyone! Up until now, every equation we solved gave us exactly one neat answer: x = 5, w = -9/4, or x = 0. "
        "These are called CONDITIONAL equations because the equation is true only under the specific condition that the variable equals that single number. "
        "Most real-world engineering and business equations are conditional: if you want a bridge to carry 50 tons, the cable tension must equal exactly one specific value. "
        "But what happens when you solve an equation and the variable mysteriously DISAPPEARS from both sides? "
        "What does it mean when all the x's vanish into thin air?\n"
        "Prof. Park: That is the big question today! When all variables cancel out, you are left comparing two numbers. "
        "That leaves you with two distinct special possibilities: "
        "Possibility 1: You are left with a FALSE mathematical statement, like 0 = 7 or 12 = 25. "
        "Can zero ever equal seven? Of course not! That is a CONTRADICTION! "
        "When an equation leads to a contradiction, there is NO number in the entire universe that can make it true. "
        "We declare: NO SOLUTION, written with the empty set symbol, a circle with a slash through it: ∅.\n"
        "TA Sora: Possibility 2: You are left with a TRUE mathematical statement, like 5 = 5 or 0 = 0. "
        "Does zero equal zero? Always! That is an IDENTITY! "
        "An identity is true for every number you could ever imagine. "
        "We declare: ALL REAL NUMBERS, written with the blackboard bold R symbol: ℝ! "
        "Today, we will master classifying equations into these three families: Conditional (one solution), Contradiction (no solution), and Identity (all real numbers). Let's begin on slide 2!"
    ),
    2: (
        "Prof. Park: On slide 2, let's examine Section 1.6 Examples 2C and 2D from workbook page 18: "
        "Solve each equation and classify it as conditional, contradiction, or identity.\n"
        "TA Sora: Let's solve Example 2C: 2(7 - x) + 11 = 12 - 2x. "
        "Step 1: Distribute 2 on the left side: 2 · 7 - 2 · x = 14 - 2x. "
        "So our equation is: 14 - 2x + 11 = 12 - 2x. "
        "Step 2: Combine like terms on the left: 14 + 11 = 25. "
        "So we get: 25 - 2x = 12 - 2x. "
        "Step 3: Move variable terms to one side by adding 2x to both sides: "
        "25 - 2x + 2x = 12 - 2x + 2x. "
        "Look what happens: -2x + 2x = 0 on BOTH sides! "
        "The variables completely vanish, leaving us with: 25 = 12!\n"
        "Prof. Park: 25 = 12 is an absolute falsehood! 25 never equals 12! "
        "Because this statement is FALSE and the variable cancelled out, this equation is a CONTRADICTION! "
        "Our answer is: NO SOLUTION (or ∅). "
        "In physical terms, this represents two parallel lines that never intersect, or two opposing physical forces that can never balance.\n"
        "TA Sora: Now let's solve Example 2D: -4 - (3 - x) - 2 = 9(x - 1) - 8x. "
        "Step 1: Distribute the negative sign on the left, and distribute 9 on the right: "
        "Left: -4 - 3 + x - 2. "
        "Right: 9x - 9 - 8x. "
        "Step 2: Combine like terms on each side independently: "
        "Left side: -4 - 3 - 2 = -9, so we have: x - 9. "
        "Right side: 9x - 8x = x, so we have: x - 9. "
        "Notice that both sides are IDENTICAL: x - 9 = x - 9! "
        "If you subtract x from both sides: -9 = -9 (or add 9 to get 0 = 0). "
        "This is ALWAYS TRUE! Therefore, this equation is an IDENTITY! "
        "Our answer is: ALL REAL NUMBERS (or ℝ)!"
    ),
    3: (
        "Prof. Park: Slide 3 takes us to In-Class Practice Problems 1 and 2 from workbook page 19: "
        "Problem 1: 3x - 2 = -9x + 15. "
        "Problem 2: r - 3 - 7 + r = 10 + 2r.\n"
        "TA Sora: Let's work Problem 1: 3x - 2 = -9x + 15. "
        "Let's move all x terms to the left by adding 9x to both sides: "
        "3x + 9x - 2 = 15, which gives: 12x - 2 = 15. "
        "Add 2 to both sides: 12x = 15 + 2 = 17. "
        "Divide both sides by 12: x = 17/12! "
        "Did the variable disappear? No! We found a single unique value: x = 17/12. "
        "Therefore, Problem 1 is classified as a CONDITIONAL equation!\n"
        "Prof. Park: Exactly right. Now let's solve Problem 2: r - 3 - 7 + r = 10 + 2r. "
        "First, combine like terms on the left side: "
        "r + r = 2r. "
        "-3 - 7 = -10. "
        "So the left side is: 2r - 10. "
        "The right side is: 10 + 2r (or 2r + 10). "
        "So our equation is: 2r - 10 = 2r + 10.\n"
        "TA Sora: Subtract 2r from both sides: "
        "2r - 2r - 10 = 2r - 2r + 10. "
        "The r's cancel out completely: -10 = +10! "
        "Does negative 10 equal positive 10? No! "
        "Owing 10 dollars is definitely not the same as having 10 dollars in your wallet! "
        "This is a FALSE statement. Therefore, Problem 2 is a CONTRADICTION! "
        "Classification: Contradiction. Solution: No Solution (∅)."
    ),
    4: (
        "Prof. Park: On slide 4, let's examine In-Class Practice Problems 3 and 4 from workbook page 19: "
        "Problem 3: 3(w - 4) = 3(w - 9) + 15. "
        "Problem 4: -4x + 4(x - 4) = -11.\n"
        "TA Sora: Let's solve Problem 3: 3(w - 4) = 3(w - 9) + 15. "
        "Step 1: Distribute 3 on both sides: "
        "Left side: 3 · w - 3 · 4 = 3w - 12. "
        "Right side: 3 · w - 3 · 9 + 15 = 3w - 27 + 15. "
        "Step 2: Combine like terms on the right side: -27 + 15 = -12. "
        "Look at our equation now: 3w - 12 = 3w - 12! "
        "Both sides are completely identical! "
        "Subtract 3w from both sides: -12 = -12. Add 12 to both sides: 0 = 0. "
        "This is a TRUE statement that holds for every number! "
        "Therefore, Problem 3 is an IDENTITY! "
        "Solution: All Real Numbers (ℝ)!\n"
        "Prof. Park: Now let's tackle Problem 4: -4x + 4(x - 4) = -11. "
        "Step 1: Distribute the 4: -4x + 4x - 16 = -11. "
        "Step 2: Combine like terms on the left: -4x + 4x = 0! "
        "The x terms cancel out to zero! "
        "We are left with: -16 = -11. "
        "Negative 16 does NOT equal negative 11! This is FALSE! "
        "Therefore, Problem 4 is a CONTRADICTION! "
        "Classification: Contradiction. Solution: No Solution (∅)."
    ),
    5: (
        "Prof. Park: Slide 5 concludes Lecture 12 with In-Class Practice Problems 5 and 6 from workbook page 19: "
        "Problem 5: -(-y - 28) = 7(y + 4). "
        "Problem 6: -2(r + 3) + 7 = 1 - 2r.\n"
        "TA Sora: Problem 5 is a favorite exam trap! Watch closely: "
        "Left side: distribute the negative sign: -(-y) - (-28) = y + 28! "
        "Right side: distribute 7: 7 · y + 7 · 4 = 7y + 28! "
        "So our equation is: y + 28 = 7y + 28. "
        "Subtract 28 from both sides: y = 7y. "
        "Subtract y from both sides: 0 = 6y. "
        "Divide by 6: y = 0 / 6 = 0!\n"
        "Prof. Park: Students often see 0 = 6y and falsely assume it has no solution or is an identity. "
        "That is completely wrong! y = 0 is a single, perfectly valid number! "
        "If you plug in y = 0: -(-0 - 28) = 28, and 7(0 + 4) = 28. 28 = 28! "
        "So Problem 5 is CONDITIONAL, with the single solution y = 0!\n"
        "TA Sora: Now let's solve Problem 6: -2(r + 3) + 7 = 1 - 2r. "
        "Distribute -2: -2r - 6 + 7 = 1 - 2r. "
        "Combine like terms on the left: -6 + 7 = +1. "
        "So the left side is: -2r + 1. "
        "The right side is: 1 - 2r (which is also -2r + 1)! "
        "Both sides are identical! Add 2r to both sides: 1 = 1. "
        "This is ALWAYS TRUE! Therefore, Problem 6 is an IDENTITY, with solution All Real Numbers (ℝ)!\n"
        "Prof. Park: In Lecture 13, we tackle Section 1.7: Solving Linear Equations with Fractions by Clearing the LCD. "
        "Outstanding work on classifying equations today, and see you in Lecture 13!"
    )
}

L13_TEXT = {
    1: (
        "Prof. Park: Welcome everyone to Lecture 13 of M090 Introductory Algebra! I am Professor Eunju Park, and joining me at the teaching desk is TA Sora. "
        "Today, we dive into Section 1.7 of our course workbook, found on pages 20 through 22: Solving Linear Equations with Fractions by Clearing the LCD.\n"
        "TA Sora: Hello everyone! If you ask algebra students across the country what topic stresses them out the most, "
        "a huge percentage will immediately say: 'Fractions in equations!' "
        "Fractions make people nervous because finding common denominators and adding fractions at every single step of an equation is tedious and prone to arithmetic mistakes. "
        "Well, today, we have the best news of the entire semester: "
        "You do NOT have to do fraction arithmetic when solving an equation! "
        "You can completely ELIMINATE all fractions in one single, glorious opening step!\n"
        "Prof. Park: That is the power of the 'Clearing Fractions Strategy.' "
        "Remember our Golden Rule of Equality: Whatever you do to one side of an equation, you must do to the other side. "
        "If you multiply BOTH sides of an equation by the Least Common Denominator (LCD) of ALL fractions in the equation, "
        "every single denominator divides evenly into that LCD and cancels out into whole integers! "
        "Your ugly fraction equation instantly transforms into a friendly, whole-number equation from Lecture 11!\n"
        "TA Sora: Notice the huge difference between Section 1.5 and Section 1.7: "
        "In Section 1.5, we had an EXPRESSION (like 1/2 x + 3/4). There was no equal sign, so we could NOT eliminate denominators—we had to keep the LCD! "
        "In Section 1.7, we have an EQUATION with an equal sign! "
        "Because there is an equal sign, we can multiply both sides by the LCD and completely vaporize the denominators! "
        "Also remember the key equivalence: (3/4)x is identically equal to (3x)/4. The x can sit next to the fraction or upstairs in the numerator, but NEVER in the denominator! "
        "Let's see this in action on slide 2!"
    ),
    2: (
        "Prof. Park: On slide 2, let's compare two different methods for solving the exact same equation from workbook page 20: "
        "(3/4)x = 15.\n"
        "TA Sora: Method 1 (Dividing by the Coefficient): "
        "x is multiplied by the fraction 3/4. "
        "To undo multiplying by 3/4, we multiply both sides by its reciprocal: 4/3! "
        "(4/3) · (3/4)x = (4/3) · 15. "
        "On the left: (4/3)(3/4) = 12/12 = 1, leaving x. "
        "On the right: (4/3) · (15/1) = (4 · 15) / 3 = 60 / 3 = 20! "
        "So x = 20. That works very nicely when there is only one single term on each side.\n"
        "Prof. Park: Now let's look at Method 2: The Method of Clearing Fractions! "
        "The only denominator in the equation is 4, so our LCD is 4. "
        "Multiply BOTH sides of the equation by 4: "
        "4 · [ (3/4)x ] = 4 · [ 15 ]. "
        "On the left side: the 4 in front cancels the 4 in the denominator: 4 · (3/4) = 3! Leaving: 3x. "
        "On the right side: 4 · 15 = 60! "
        "Now we have the simplest one-step equation imaginable: 3x = 60! "
        "Divide both sides by 3: x = 60 / 3 = 20!\n"
        "TA Sora: Notice how much easier Method 2 is when equations get longer! "
        "Instead of carrying fractions through multiple steps, you multiply by 4 on step 1, and you're dealing with clean, easy whole numbers: 3x = 60, x = 20. "
        "Method 2 is our standard protocol for the rest of this chapter!"
    ),
    3: (
        "Prof. Park: Slide 3 presents Section 1.7 Examples 3A and 3B from workbook page 20: "
        "Example 3A: x / (-5) = 10. "
        "Example 3B: (1/2)y + 3/4 = 10.\n"
        "TA Sora: In Example 3A: x / (-5) = 10. "
        "x is divided by -5. The denominator is -5. "
        "To clear the denominator, multiply both sides by -5: "
        "(-5) · [ x / (-5) ] = (-5) · [ 10 ]. "
        "On the left, -5 cancels -5, leaving x. "
        "On the right: (-5)(10) = -50! "
        "So x = -50. Check: -50 / -5 = +10. Perfect!\n"
        "Prof. Park: Now look at Example 3B: (1/2)y + 3/4 = 10. "
        "Notice there are THREE terms in this equation: (1/2)y, +3/4, and 10! "
        "The denominators are 2 and 4. What is the LCD of 2 and 4? It is 4! "
        "Now listen carefully to Sora's Golden Warning:\n"
        "TA Sora: Golden Warning! When you clear fractions, you must multiply EVERY SINGLE TERM on both sides by the LCD—even terms that are NOT fractions! "
        "The number 10 on the right side does NOT have a fraction, but it MUST still be multiplied by 4! "
        "If you multiply the left side by 4 and forget to multiply the 10 by 4, your scale will tip and your answer will be totally wrong!\n"
        "Prof. Park: Let's multiply every term by 4: "
        "4 · [ (1/2)y ] + 4 · [ 3/4 ] = 4 · [ 10 ]. "
        "First term: 4 · (1/2) = 2, so we get 2y. "
        "Second term: 4 · (3/4) = 3, so we get +3. "
        "Third term: 4 · 10 = 40! "
        "Look at our new equation: 2y + 3 = 40! All fractions are gone!\n"
        "TA Sora: Now solve: subtract 3 from both sides: 2y = 40 - 3 = 37. "
        "Divide by 2: y = 37/2! "
        "Clean, elegant, and solved in seconds!"
    ),
    4: (
        "Prof. Park: On slide 4, we examine Section 1.7 Examples 3C and 3D from workbook page 21: "
        "Example 3C: (1/2)x - 2/7 = 5/4 - x. "
        "Example 3D: 3/5 + x/5 = 18.\n"
        "TA Sora: Let's analyze Example 3C: (1/2)x - 2/7 = 5/4 - x. "
        "Look at the denominators: 2, 7, and 4. "
        "What is the LCD of 2, 7, and 4? "
        "Between 2 and 4, the LCM is 4. "
        "Between 4 and 7, they share no common factors, so 4 · 7 = 28! "
        "Our LCD is 28! "
        "Now, multiply EVERY SINGLE TERM by 28: "
        "28 · [ (1/2)x ] - 28 · [ 2/7 ] = 28 · [ 5/4 ] - 28 · [ x ].\n"
        "Prof. Park: Let's simplify each product carefully: "
        "First term: 28 / 2 = 14, so 14x. "
        "Second term: 28 / 7 = 4, and 4 · 2 = 8, so -8. "
        "Third term: 28 / 4 = 7, and 7 · 5 = 35, so 35. "
        "Fourth term: 28 · x = 28x, so -28x. "
        "Our equation is now: 14x - 8 = 35 - 28x!\n"
        "TA Sora: That is wonderful! Add 28x to both sides: 14x + 28x - 8 = 35, which gives 42x - 8 = 35. "
        "Add 8 to both sides: 42x = 35 + 8 = 43. "
        "Divide both sides by 42: x = 43/42! "
        "Imagine how messy that would have been if you tried to find common denominators and add fractions across the equal sign four times! "
        "Clearing fractions with LCD = 28 made it effortless.\n"
        "Prof. Park: Now look at Example 3D: 3/5 + x/5 = 18. "
        "The denominator is 5. Multiply every term by 5: "
        "5 · (3/5) + 5 · (x/5) = 5 · (18). "
        "3 + x = 90! "
        "Subtract 3 from both sides: x = 90 - 3 = 87! Done!"
    ),
    5: (
        "Prof. Park: Slide 5 presents Section 1.7 Example 3E on workbook page 21: "
        "Clearing Fractions when Parentheses are Present: "
        "(1/7)(x - 4) + 5 = (1/2)(3x + 4).\n"
        "TA Sora: Warning! Look at the expression (1/7)(x - 4). "
        "Is (x - 4) a separate term? NO! "
        "(1/7)(x - 4) is ONE SINGLE TERM because 1/7 is multiplied by (x - 4)! "
        "When you multiply this term by the LCD, you multiply the fraction 1/7 in FRONT of the parentheses! "
        "Do NOT multiply inside the parentheses yet!\n"
        "Prof. Park: That is such a crucial distinction. The denominators are 7 and 2. "
        "The LCD of 7 and 2 is 14. "
        "Let's multiply every term by 14: "
        "14 · [ (1/7)(x - 4) ] + 14 · [ 5 ] = 14 · [ (1/2)(3x + 4) ]. "
        "Look at the first term: 14 · (1/7) = 2! So it becomes: 2(x - 4). "
        "Second term: 14 · 5 = 70. "
        "Right side: 14 · (1/2) = 7! So it becomes: 7(3x + 4). "
        "Our equation is now: 2(x - 4) + 70 = 7(3x + 4)!\n"
        "TA Sora: Look how clean that is! All fractions are gone, and now we just use our standard distribution from Lecture 11: "
        "Left: 2x - 8 + 70 = 2x + 62. "
        "Right: 21x + 28. "
        "So we have: 2x + 62 = 21x + 28. "
        "Subtract 2x from both sides: 62 = 19x + 28. "
        "Subtract 28 from both sides: 34 = 19x. "
        "Divide by 19: x = 34/19! "
        "What a magnificent, orderly solution!"
    ),
    6: (
        "Prof. Park: Slide 6 concludes Lecture 13 with Section 1.7 Examples 3F and 3G from workbook page 22: "
        "Example 3F: (x - 7) / 8 = 5/6. "
        "Example 3G: (1/3)(3m + 1) = (1/4)(m - 4) + 1.\n"
        "TA Sora: Let's look at Example 3F: (x - 7) / 8 = 5/6. "
        "This is a single fraction equal to a single fraction—a proportion! "
        "The denominators are 8 and 6. The LCD of 8 and 6 is 24! "
        "Multiply both sides by 24: "
        "24 · [ (x - 7) / 8 ] = 24 · [ 5/6 ]. "
        "On the left: 24 / 8 = 3, so we have: 3(x - 7). "
        "On the right: 24 / 6 = 4, and 4 · 5 = 20! "
        "So our equation is: 3(x - 7) = 20. "
        "Distribute: 3x - 21 = 20. "
        "Add 21 to both sides: 3x = 41. "
        "Divide by 3: x = 41/3!\n"
        "Prof. Park: Now let's solve Example 3G: (1/3)(3m + 1) = (1/4)(m - 4) + 1. "
        "Denominators are 3 and 4, so the LCD is 12! "
        "Multiply EVERY term by 12: "
        "12 · [ (1/3)(3m + 1) ] = 12 · [ (1/4)(m - 4) ] + 12 · [ 1 ]. "
        "Left: 12 · (1/3) = 4, so: 4(3m + 1). "
        "Right first term: 12 · (1/4) = 3, so: 3(m - 4). "
        "Right second term: 12 · 1 = 12. "
        "So we have: 4(3m + 1) = 3(m - 4) + 12. "
        "Distribute: 12m + 4 = 3m - 12 + 12. "
        "-12 + 12 = 0, so: 12m + 4 = 3m. "
        "Subtract 12m from both sides: 4 = -9m. "
        "Divide by -9: m = -4/9!\n"
        "TA Sora: That concludes Section 1.7! In Lecture 14, we will master Section 1.8: Solving Formulas for a Specified Variable. "
        "Great job everyone, and we will see you in Lecture 14!"
    )
}

L14_TEXT = {
    1: (
        "Prof. Park: Welcome everyone to Lecture 14 of M090 Introductory Algebra! I am Professor Eunju Park, and joining me at the teaching desk is TA Sora. "
        "Today, we turn to Section 1.8 on workbook pages 23 and 24: Solving Formulas for a Specified Variable—Literal Equations.\n"
        "TA Sora: Hello everyone! Up until today, most equations had one letter (like x) and several numbers (like 3x + 5 = 20). "
        "Today, we encounter formulas that contain MULTIPLE variables—like d = rt, P = 2L + 2W, or Ax + By = C. "
        "These are called literal equations or formulas because they are written with letters ('litera' in Latin). "
        "Students are often intimidated by literal equations because there aren't many numbers to calculate. "
        "They ask: 'How can I solve for y if I don't know what x or z equals?'\n"
        "Prof. Park: The secret is simple: Treat all other letters exactly like known constants! "
        "Ask yourself: 'If that letter were the number 5, what operation would I use to move it?' "
        "If you would subtract 5, then subtract x! If you would divide by 3, then divide by m! "
        "The algebraic rules never change—only the symbols do!\n"
        "TA Sora: In real Montana careers, you do this all the time: "
        "In agriculture, irrigation water rights formulas are solved for flow duration t. "
        "In forestry and wildlife biology, timber board-foot formulas are solved for usable log diameter d. "
        "In construction across Gallatin County, perimeter and load formulas are rearranged to calculate beam length L. "
        "Today, we will master isolating any target variable with 100% confidence. Let's begin on slide 2!"
    ),
    2: (
        "Prof. Park: On slide 2, let's examine Section 1.8 Examples 1A and 1B on workbook page 23: "
        "Solving standard linear equations for y. "
        "Part A: 3x + y = 8. "
        "Part B: 2x - 5y = 12.\n"
        "TA Sora: In Part A, we want to isolate y: 3x + y = 8. "
        "Look at what is on the same side as y: we have a positive 3x added to y. "
        "To eliminate +3x, what is the inverse operation? Subtract 3x from both sides! "
        "3x + y - 3x = 8 - 3x. "
        "On the left, 3x - 3x = 0, leaving y isolated! "
        "On the right: Can you combine 8 and -3x into 5x? "
        "ABSOLUTELY NOT! 8 is a constant and -3x has a variable—they are NOT like terms! "
        "You simply write them side-by-side: y = 8 - 3x (or y = -3x + 8). "
        "Done in one step!\n"
        "Prof. Park: Now let's solve Part B: 2x - 5y = 12. We want to isolate y. "
        "Step 1: Get the y term (-5y) alone by subtracting 2x from both sides: "
        "-5y = 12 - 2x (or -5y = -2x + 12). "
        "Step 2: y is multiplied by -5. Divide BOTH sides by -5: "
        "y = (-2x + 12) / (-5). "
        "Now distribute the division by -5 to both terms: "
        "-2x / -5 = +(2/5)x. "
        "+12 / -5 = -12/5. "
        "So y = (2/5)x - 12/5 (or (2x - 12) / 5). "
        "Notice that dividing by -5 changed the signs upstairs: -2x became positive 2x, and +12 became -12. "
        "This form—y = mx + b—is the famous slope-intercept form we will use extensively in Unit 2!"
    ),
    3: (
        "Prof. Park: Slide 3 covers Section 1.8 Examples 1C and 1D on workbook page 23: "
        "Part C: Z = x + wxy; solve for y. "
        "Part D: 5xy = 19; solve for y.\n"
        "TA Sora: Look at Part C: Z = x + wxy. We want to isolate y. "
        "Notice where y lives: y is inside the term wxy! "
        "Step 1: Isolate the term containing y. Subtract x from both sides: "
        "Z - x = wxy. "
        "Step 2: What is multiplying y? Both w and x are multiplying y: (wx) · y! "
        "The inverse of multiplying by wx is dividing by wx! "
        "Divide both sides by wx: "
        "(Z - x) / (wx) = y. "
        "So y = (Z - x) / (wx)! "
        "Can we cancel the x in the numerator with the x in the denominator? "
        "NO! Z - x is a subtraction! You can only cancel common factors, never terms attached by minus!\n"
        "Prof. Park: Now look at Part D: 5xy = 19. Solve for y. "
        "y is multiplied by 5 and x: (5x) · y = 19. "
        "To isolate y in one step, divide both sides by 5x: "
        "y = 19 / (5x). "
        "Simple, direct, and completely isolated!"
    ),
    4: (
        "Prof. Park: On slide 4, let's examine Section 1.8 Examples 2A and 2B on workbook page 23: "
        "Solving for specified variable b: "
        "Part A: a + b - c = d; solve for b. "
        "Part B: ax^2 + bx + c = 0; solve for b.\n"
        "TA Sora: In Part A: a + b - c = d. We want to isolate b. "
        "What is attached to b? We have +a and -c. "
        "To undo +a, subtract a from both sides. "
        "To undo -c, add c to both sides! "
        "So b = d - a + c! "
        "Notice that every term moved across the equal sign simply took its opposite sign: +a became -a, and -c became +c!\n"
        "Prof. Park: Now look at Part B: ax^2 + bx + c = 0. Solve for b. "
        "This looks like the general quadratic equation from advanced algebra! "
        "Our target variable is b, which is inside the middle term bx. "
        "Step 1: Isolate the term bx by moving all other terms to the right side: "
        "Subtract ax^2 from both sides: -ax^2. "
        "Subtract c from both sides: -c. "
        "So we get: bx = -ax^2 - c. "
        "Step 2: To isolate b, divide both sides by x: "
        "b = (-ax^2 - c) / x (or b = -ax - c/x). "
        "That is our complete solution for b!"
    ),
    5: (
        "Prof. Park: Slide 5 presents Section 1.8 Examples 2C and 2D on workbook page 24: "
        "Solving fractional formulas for r: "
        "Part C: m = (r - 7n) / 5; solve for r. "
        "Part D: t = d / r; solve for r.\n"
        "TA Sora: Look at Part C: m = (r - 7n) / 5. Our target is r, but r is trapped inside a fraction! "
        "How do we free r from the fraction? Clear the fraction! "
        "Multiply both sides by the denominator 5: "
        "5 · m = 5 · [ (r - 7n) / 5 ]. "
        "On the right, the 5 cancels, leaving: 5m = r - 7n. "
        "Now add 7n to both sides to isolate r: "
        "r = 5m + 7n! "
        "Multiplying by the denominator first immediately freed our variable!\n"
        "Prof. Park: Now look at Part D: t = d / r. Solve for r. "
        "This is the famous distance, rate, and time formula from physics: time = distance / rate! "
        "For example, driving 90 miles on Interstate 90 from Bozeman to Butte at speed r takes time t. "
        "Notice where r is: r is trapped DOWNSTAIRS in the denominator! "
        "You can NEVER solve for a variable while it is in the denominator!\n"
        "TA Sora: Step 1: Get r out of the basement! Multiply both sides by r: "
        "r · t = r · (d / r) = d. "
        "So we get: rt = d (distance = rate times time). "
        "Step 2: Now that r is upstairs, isolate r by dividing both sides by t: "
        "r = d / t! "
        "Speed equals distance divided by time. Clean, intuitive, and physically meaningful!"
    ),
    6: (
        "Prof. Park: On slide 6, we explore geometric formulas from workbook page 24: "
        "Part E: P = 2L + 2W; solve for W. "
        "Part F: V = LWH; solve for W.\n"
        "TA Sora: Part E is the perimeter formula for a rectangle: Perimeter = 2 times Length + 2 times Width. "
        "Imagine fencing a horse pasture in the Gallatin Valley: you know the total perimeter fencing P you bought, and you know the pasture length L. "
        "How wide can the pasture be? We must solve for W! "
        "Step 1: Isolate the 2W term by subtracting 2L from both sides: "
        "P - 2L = 2W. "
        "Step 2: Divide both sides by 2: "
        "W = (P - 2L) / 2 (or W = P/2 - L). "
        "Can the 2 in 2L cancel with the 2 in the denominator? "
        "NO! P is not multiplied by 2! You cannot cancel unless BOTH terms share the factor 2!\n"
        "Prof. Park: Now look at Part F: V = LWH. Solve for W. "
        "This is the volume formula for a rectangular prism (like a timber beam or concrete foundation footer): Volume = Length times Width times Height. "
        "W is multiplied by both L and H: (LH) · W = V. "
        "To isolate W, divide both sides by LH: "
        "W = V / (LH)! "
        "Width equals volume divided by the product of length and height."
    ),
    7: (
        "Prof. Park: Slide 7 concludes Lecture 14 with our Section 1.8 Review Problems from workbook page 24: "
        "Solving equations by clearing fractions: "
        "Review A: (y - 2) / 5 = (3/2)y + 4/5. "
        "Review B: 2/7 = (3/7)(x - 4) - 5/7.\n"
        "TA Sora: Let's solve Review A: (y - 2) / 5 = (3/2)y + 4/5. "
        "Look at the denominators: 5, 2, and 5. The LCD is 10! "
        "Multiply every term by 10: "
        "10 · [ (y - 2) / 5 ] = 10 · [ (3/2)y ] + 10 · [ 4/5 ]. "
        "First term: 10 / 5 = 2, so 2(y - 2) = 2y - 4. "
        "Second term: 10 · (3/2) = 15y. "
        "Third term: 10 · (4/5) = 8. "
        "So we get: 2y - 4 = 15y + 8. "
        "Subtract 2y from both sides: -4 = 13y + 8. "
        "Subtract 8 from both sides: -12 = 13y. "
        "Divide by 13: y = -12/13!\n"
        "Prof. Park: Now let's solve Review B: 2/7 = (3/7)(x - 4) - 5/7. "
        "All denominators are 7, so the LCD is 7! "
        "Multiply every term by 7: "
        "2 = 3(x - 4) - 5. "
        "Distribute: 2 = 3x - 12 - 5. "
        "Combine like terms: 2 = 3x - 17. "
        "Add 17 to both sides: 19 = 3x. "
        "Divide by 3: x = 19/3! "
        "In Lecture 15, we conclude Unit 1 with Section 1.9: Solving Linear Inequalities and Interval Notation! "
        "Fantastic work today, and see you in Lecture 15!"
    )
}

L15_TEXT = {
    1: (
        "Prof. Park: Welcome everyone to Lecture 15 of M090 Introductory Algebra! I am Professor Eunju Park, and joining me at the teaching desk is TA Sora. "
        "Today is a celebration: we complete Section 1.9 on workbook pages 25 through 27: Solving Linear Inequalities, Graphing on Number Lines, and Interval Notation—and we conduct our Grand Unit 1 Review!\n"
        "TA Sora: Hello everyone! Today we transition from equations (where two sides are equal) to INEQUALITIES (where one side is strictly greater than, less than, or equal to the other side). "
        "In real life, conditions are rarely exact equalities. "
        "When civil engineers design the bridge over the Gallatin River on Interstate 90, the load limit is an inequality: Weight ≤ 80,000 pounds. "
        "When backcountry skiers check avalanche danger at Bridger Bowl, snowpack temperature must stay below freezing: T < 32° Fahrenheit. "
        "Today, we learn how to solve inequalities, express their infinite solution sets on number lines, and write them in standard INTERVAL NOTATION!\n"
        "Prof. Park: And we must introduce the single most famous rule in all of inequality algebra: "
        "The Golden Rule of Inequalities: When you MULTIPLY or DIVIDE both sides of an inequality by a NEGATIVE number, you MUST REVERSE (FLIP) the inequality symbol! "
        "If it was less than, it becomes greater than! If it was greater than or equal to, it becomes less than or equal to! "
        "Sora, explain why this flip happens with simple numbers.\n"
        "TA Sora: Look at 2 and 5. We all agree that 2 < 5. "
        "Now multiply both numbers by -1: 2 becomes -2, and 5 becomes -5. "
        "Which is larger: owing 2 dollars or owing 5 dollars? -2 is larger than -5! "
        "So -2 > -5! The symbol FLIPPED from less-than to greater-than! "
        "Multiplying by a negative reflects the numbers across zero to the opposite side of the number line, reversing their relative order! "
        "Remember: only flip the symbol when you multiply or divide by a NEGATIVE number. Let's begin on slide 2!"
    ),
    2: (
        "Prof. Park: Slide 2 covers Section 1.9 Examples 1A and 1B from workbook page 25: "
        "Basic Interval Notation and Number Line Graphing: "
        "Part A: x > 5. "
        "Part B: x < -6.\n"
        "TA Sora: Let's master our notation conventions: "
        "Strict inequalities (< and >) use an OPEN circle on the graph and PARENTHESES ( ) in interval notation because the boundary endpoint is NOT included! "
        "Inclusive inequalities (≤ and ≥) use a CLOSED (solid) circle or square bracket [ ] because the boundary endpoint IS included! "
        "And infinity (∞) and negative infinity (-∞) ALWAYS take parentheses ( ) because infinity is a direction, not a reachable number!\n"
        "Prof. Park: Now let's graph Part A: x > 5. "
        "On the number line, place an open parenthesis at 5 and shade everything to the RIGHT toward positive infinity. "
        "In interval notation, read from left to right: (5, ∞). "
        "Now look at Part B: x < -6. "
        "Place an open parenthesis at -6 and shade everything to the LEFT toward negative infinity. "
        "Reading from left to right: (-∞, -6). "
        "Always write the smaller (leftmost) number first in interval notation!"
    ),
    3: (
        "Prof. Park: On slide 3, we look at Section 1.9 Examples 1C and 1D on workbook page 25: "
        "Inequalities with the variable on the RIGHT side: "
        "Part C: -3 ≤ x. "
        "Part D: 12 ≥ x.\n"
        "TA Sora: Danger alert! When the variable is on the right side, students often shade in the wrong direction! "
        "In Part C: -3 ≤ x. Read it from the variable's perspective: 'x is GREATER THAN OR EQUAL TO -3!' "
        "If you flip the sides to put x on the left, remember that the inequality mouth stays open toward x: x ≥ -3! "
        "Now it is crystal clear: at -3, place a solid bracket [ and shade to the RIGHT! "
        "In interval notation: [-3, ∞)!\n"
        "Prof. Park: Now look at Part D: 12 ≥ x. "
        "Read it starting with x: 'x is LESS THAN OR EQUAL TO 12!' "
        "Rewriting with x on the left: x ≤ 12. "
        "On the number line, place a solid bracket ] at 12 and shade to the LEFT toward -∞. "
        "In interval notation: (-∞, 12]! "
        "Always rewrite inequalities with the variable on the left if you are ever unsure of the shading direction."
    ),
    4: (
        "Prof. Park: Slide 4 covers Section 1.9 Examples 1E and 1F on workbook page 25: "
        "Double (Bounded) Inequalities: "
        "Part E: -3 < x < 1. "
        "Part F: 2 ≤ x < 3.\n"
        "TA Sora: A double inequality describes a bounded interval sandwiched between two finite endpoints! "
        "In Part E: -3 < x < 1. "
        "x is simultaneously greater than -3 AND less than 1! "
        "On the number line, shade the region strictly BETWEEN -3 and 1. "
        "Since both symbols are strict (<), use parentheses on both ends: (-3, 1)!\n"
        "Prof. Park: Now look at Part F: 2 ≤ x < 3. "
        "Here, 2 is included (≤), but 3 is excluded (<)! "
        "At 2, place a solid bracket [ . At 3, place an open parenthesis ) . "
        "Shade between 2 and 3. "
        "In interval notation: [2, 3)! "
        "This is called a half-open interval. In agricultural quality control, grain moisture content must often fall into bounded intervals like this to prevent spoilage during winter storage."
    ),
    5: (
        "Prof. Park: On slide 5, we examine Section 1.9 Examples 1G and 1H: "
        "Disjoint Compound Inequalities using the Union Symbol (∪): "
        "Part G: x < -7 or x ≥ 0. "
        "Part H: x ≤ 2 or x > 5.\n"
        "TA Sora: When you see the word 'OR', the solution set consists of two separate, non-overlapping intervals! "
        "In Part G: x < -7 OR x ≥ 0. "
        "First piece: x < -7 is (-∞, -7). "
        "Second piece: x ≥ 0 is [0, ∞). "
        "To combine them into a single mathematical statement, we use the UNION operator ∪ (which looks like a capital U): "
        "(-∞, -7) ∪ [0, ∞)!\n"
        "Prof. Park: Now look at Part H: x ≤ 2 or x > 5. "
        "Left piece: x ≤ 2 gives (-∞, 2]. "
        "Right piece: x > 5 gives (5, ∞). "
        "United together: (-∞, 2] ∪ (5, ∞). "
        "The union symbol represents 'taking everything in either set.'"
    ),
    6: (
        "Prof. Park: Slide 6 moves to Section 1.9 Examples 2A and 2B on workbook page 26: "
        "Solving Linear Inequalities algebraically: "
        "Part A: -6 + 3x ≤ -12 + 5x. "
        "Part B: 4(5x - 7) > 10 + 5x.\n"
        "TA Sora: Solving inequalities follows the exact same balance scale steps as solving equations, with one exception: watch out for dividing by a negative! "
        "Let's solve Part A: -6 + 3x ≤ -12 + 5x. "
        "Subtract 5x from both sides: -6 - 2x ≤ -12. "
        "Add 6 to both sides: -2x ≤ -6. "
        "Now divide both sides by -2: "
        "DANGER! We are dividing by NEGATIVE 2! "
        "FLIP the symbol from ≤ to ≥! "
        "x ≥ (-6) / (-2) = 3! "
        "So x ≥ 3. In interval notation: [3, ∞)!\n"
        "Prof. Park: Now let's solve Part B: 4(5x - 7) > 10 + 5x. "
        "Distribute the 4: 20x - 28 > 10 + 5x. "
        "Subtract 5x from both sides: 15x - 28 > 10. "
        "Add 28 to both sides: 15x > 38. "
        "Divide by positive 15: since 15 is positive, do NOT flip the symbol! "
        "x > 38/15. In interval notation: (38/15, ∞)!"
    ),
    7: (
        "Prof. Park: Slide 7 presents Section 1.9 Examples 2C and 2D on workbook page 26: "
        "Inequalities with Fractions and Negative Denominators: "
        "Part C: (4/5)y + 5 < 6. "
        "Part D: 2 ≤ x / (-8) - 3.\n"
        "TA Sora: In Part C: (4/5)y + 5 < 6. "
        "Subtract 5 from both sides: (4/5)y < 1. "
        "Multiply both sides by reciprocal 5/4: y < 5/4. "
        "In interval notation: (-∞, 5/4)!\n"
        "Prof. Park: Now look at Part D: 2 ≤ x / (-8) - 3. "
        "Add 3 to both sides: 5 ≤ x / (-8). "
        "To clear the denominator, multiply both sides by -8! "
        "DANGER! Multiplying by -8 FLIPS the inequality symbol from ≤ to ≥! "
        "5 · (-8) ≥ x, which gives: -40 ≥ x! "
        "Reading from x: x ≤ -40! "
        "In interval notation: (-∞, -40]! "
        "That symbol flip was critical!"
    ),
    8: (
        "Prof. Park: Slide 8 features Section 1.9 Examples 2E and 2F on workbook page 26: "
        "A side-by-side comparison of positive vs. negative denominators: "
        "Part E: (x - 30) / (-4) ≥ 50. "
        "Part F: (x - 30) / 4 > 50.\n"
        "TA Sora: Look at Part E: (x - 30) / (-4) ≥ 50. "
        "Multiply both sides by -4: this FLIPS the symbol from ≥ to ≤! "
        "x - 30 ≤ 50 · (-4) = -200. "
        "Add 30 to both sides: x ≤ -200 + 30 = -170! "
        "Interval notation: (-∞, -170]!\n"
        "Prof. Park: Now look at Part F: (x - 30) / 4 > 50. "
        "Multiply both sides by +4: since 4 is positive, do NOT flip the symbol! "
        "x - 30 > 50 · 4 = 200. "
        "Add 30 to both sides: x > 230! "
        "Interval notation: (230, ∞)! "
        "Look at the dramatic difference: Part E yields numbers below -170, while Part F yields numbers above +230! "
        "That single negative sign completely inverted the entire solution domain!"
    ),
    9: (
        "Prof. Park: Slide 9 concludes Lecture 15 and marks the completion of Unit 1! "
        "Let's celebrate everyone's incredible dedication across Sections 1.0 through 1.9 with Sora's 10 Core Commandments of Algebra!\n"
        "TA Sora: Here are our 10 Golden Commandments: "
        "1. Order of Operations: PEMDAS always rules—parentheses, exponents, multiply/divide left to right, add/subtract left to right! "
        "2. Substitution: Always wrap substituted numbers in protective parentheses to preserve signs! "
        "3. Exponents: Product rule adds powers, quotient rule subtracts powers, negative exponents take the elevator! "
        "4. Distributive Property: Watch minus signs in front of parentheses—they flip every sign inside! "
        "5. Polynomial Multiplication: Binomial squared has a middle term! (a + b)^2 = a^2 + 2ab + b^2! "
        "6. Rational Expressions: Add and subtract ONLY over a common denominator! "
        "7. Linear Equations: The balance scale rule—isolate the variable using inverse operations! "
        "8. Clearing Fractions: Multiply every term on both sides by the LCD to eliminate all fractions in one step! "
        "9. Equation Classification: Conditional (one solution), Identity (all real numbers), Contradiction (no solution)! "
        "10. Inequalities: FLIP the inequality symbol whenever you multiply or divide by a negative number!\n"
        "Prof. Park: With these 10 commandments etched into your algebraic toolbox, you are 100% prepared for Unit 2: Linear Equations in Two Variables and Graphing. "
        "Congratulations on conquering Unit 1 of M090 Introductory Algebra!"
    )
}

# Write out unit1_scripts_l11_l13.py
with open('Montana_State_Univ/scripts/unit1_scripts_l11_l13.py', 'w', encoding='utf-8') as f:
    f.write('# -*- coding: utf-8 -*-\n')
    f.write('"""\nunit1_scripts_l11_l13.py\nHigh-volume 20-25 minute broadcast tiki-taka scripts for Lectures 11, 12, and 13.\n"""\n\n')
    f.write('SCRIPTS_L11 = ' + json.dumps(L11_TEXT, indent=4, ensure_ascii=False) + '\n\n')
    f.write('SCRIPTS_L12 = ' + json.dumps(L12_TEXT, indent=4, ensure_ascii=False) + '\n\n')
    f.write('SCRIPTS_L13 = ' + json.dumps(L13_TEXT, indent=4, ensure_ascii=False) + '\n')

# Write out unit1_scripts_l14_l15.py
with open('Montana_State_Univ/scripts/unit1_scripts_l14_l15.py', 'w', encoding='utf-8') as f:
    f.write('# -*- coding: utf-8 -*-\n')
    f.write('"""\nunit1_scripts_l14_l15.py\nHigh-volume 20-25 minute broadcast tiki-taka scripts for Lectures 14 and 15.\n"""\n\n')
    f.write('SCRIPTS_L14 = ' + json.dumps(L14_TEXT, indent=4, ensure_ascii=False) + '\n\n')
    f.write('SCRIPTS_L15 = ' + json.dumps(L15_TEXT, indent=4, ensure_ascii=False) + '\n')

print("Batch 3 scripts successfully generated.")
