# -*- coding: utf-8 -*-
"""
build_unit1_batch2_full_25m.py
Generates full 20-25 minute broadcast tiki-taka scripts for Lectures 06 through 10.
Target: 2,280 - 2,550 words per lecture.
"""
import os
import json

L06_TEXT = {
    1: (
        "Prof. Park: Welcome everyone to Lecture 06 of M090 Introductory Algebra! I am Professor Eunju Park, and joining me at the teaching desk is our graduate teaching assistant, Sora.\n"
        "TA Sora: Hello everyone! Today, we complete Section 1.2 on workbook pages 10 and 11: Negative Exponents, Power Rules, and Master Simplifications. "
        "Today is where all our exponent knowledge comes together into an unstoppable algebraic toolkit. "
        "Students are often frightened when they first see negative exponents—they mistakenly assume that a negative exponent turns the entire number negative. "
        "That is completely untrue! A negative exponent has nothing to do with whether a number is positive or negative. "
        "A negative exponent is simply an elevator pass: it tells a factor to take the elevator across the fraction bar to the opposite floor!\n"
        "Prof. Park: That is such an intuitive analogy, Sora! Right here in Bozeman, our local optics and photonics industry—often called 'Photonics Valley'—"
        "develops ultra-precise lasers for scientific research, atmospheric monitoring, and aerospace sensors. "
        "Engineers measuring laser wavelengths routinely work with numbers like 5 times 10 to the negative 7 meters, "
        "and semiconductor physicists measure electron mass at 9.1 times 10 to the negative 31 kilograms. "
        "Negative exponents represent small, precision scales, not negative debt. "
        "Today, we will master the elevator rule, the power of a power rule, and tackle the grand master multi-variable simplifications on workbook page 11. Let's begin on slide 2!"
    ),
    2: (
        "Prof. Park: On slide 2, we introduce the Negative Exponent Property: a^(-n) = 1 / (a^n), and conversely 1 / (a^(-n)) = a^n, where the base a is non-zero. "
        "Sora, explain the elevator ticket rule in detail for our students.\n"
        "TA Sora: Think of a fraction as a two-story building: the penthouse upstairs is the numerator, and the ground floor downstairs is the denominator. "
        "Whenever a factor has a negative exponent, it is unhappy with its current floor! "
        "Its negative sign is literally a ticket that says: 'Move me to the other floor!' "
        "If an expression like x^(-3) is upstairs in the numerator, you move it downstairs to the denominator, and upon arrival, the ticket is punched—the negative exponent turns into a positive 3: 1 / (x^3).\n"
        "Prof. Park: And what happens if the negative exponent is already downstairs in the denominator, like 1 / (y^(-4))?\n"
        "TA Sora: Then it takes the elevator upstairs to the numerator! It becomes y^(+4) in the penthouse, and its denominator becomes 1. "
        "Notice two crucial golden rules: "
        "First, moving a factor across the fraction bar changes ONLY the sign of the exponent, NEVER the sign of the base! "
        "If you have (-5)^(-3), the negative 5 stays negative 5—it simply moves downstairs as 1 / [ (-5)^3 ]. "
        "Second, only factors with negative exponents move. Factors with positive exponents stay right where they are. Let's practice with Example 4 on slide 3!"
    ),
    3: (
        "Prof. Park: Let's examine Section 1.2 Example 4 Parts A, B, and C on workbook page 10: "
        "Part A: x^(-4). "
        "Part B: 3^(-2). "
        "Part C: (-5)^(-2).\n"
        "TA Sora: In Part A, x^(-4) is in the numerator. "
        "We send x downstairs to the denominator, and the exponent becomes positive 4: 1 / (x^4). Simple, clean, and done!\n"
        "Prof. Park: Now look at Part B: 3^(-2). "
        "A common student mistake is to multiply 3 by -2 and write -6. That is completely wrong! "
        "The negative sign belongs to the exponent, so it sends the base 3 downstairs: 1 / (3^2). "
        "Now 3 squared is 9, so our answer is 1/9! "
        "Notice that 1/9 is a positive fraction—the negative exponent never made the number negative.\n"
        "TA Sora: Now compare Part B with Part C: (-5)^(-2). "
        "Here, the base is -5 inside parentheses. "
        "The negative exponent -2 sends the entire base (-5) downstairs: 1 / [ (-5)^2 ]. "
        "Downstairs, (-5)^2 is (-5)(-5) = +25! "
        "So our final answer is 1/25.\n"
        "Prof. Park: Sora, what happens if someone asks about 0^(-2)? Can zero have a negative exponent?\n"
        "TA Sora: That is a brilliant question! If you try 0^(-2), the elevator rule sends zero downstairs: 1 / (0^2) = 1/0! "
        "And from Lecture 02, we know dividing by zero is strictly UNDEFINED! "
        "That is why our exponent property explicitly specifies that the base a can NEVER be zero. "
        "For all non-zero bases, the elevator rule works flawlessly and predictably every single time."
    ),
    4: (
        "Prof. Park: Now let's examine Example 4 Parts D, E, and F on slide 4: "
        "Part D: -5^(-2). "
        "Part E: 1 / (x^(-6)). "
        "Part F: (2/3)^(-3).\n"
        "TA Sora: Look at Part D: -5^(-2) without parentheses! "
        "Remember our base identification rule from Lecture 02: the exponent -2 applies ONLY to the number 5, NOT the negative sign out front! "
        "So the negative sign stays out front as -1. The 5 moves downstairs: - [ 1 / (5^2) ] = -1/25. "
        "Compare Part C: (-5)^(-2) = +1/25, whereas Part D: -5^(-2) = -1/25. That distinction is guaranteed to appear on your exam!\n"
        "Prof. Park: Now look at Part E: 1 / (x^(-6)). "
        "Here, x^(-6) is downstairs in the denominator. "
        "It takes the elevator upstairs to the numerator, and the exponent becomes positive 6: x^6 / 1 = x^6!\n"
        "TA Sora: And look at Part F: (2/3)^(-3). A fraction raised to a negative power! "
        "When an entire fraction is raised to a negative exponent, the negative power flips the entire fraction to its reciprocal! "
        "(2/3)^(-3) becomes (3/2)^(+3). "
        "Now cube both top and bottom: 3^3 / 2^3 = 27/8! "
        "Flipping the fraction uses up the negative sign instantly. What a brilliant shortcut! "
        "Think of it as turning an hourglass upside down: the sand that was on top is now on the bottom, and the timer starts fresh. "
        "Whenever an entire rational fraction is wrapped in parentheses with a negative power, flip first, then distribute."
    ),
    5: (
        "Prof. Park: Slide 5 introduces the Power Rules: "
        "1. Power of a Power: (a^m)^n = a^(m · n). "
        "2. Power of a Product: (ab)^n = a^n · b^n. "
        "3. Power of a Quotient: (a/b)^n = a^n / b^n.\n"
        "TA Sora: Let's explain why (a^m)^n means multiplying exponents! "
        "Take (a^2)^3. What does that mean? "
        "It means taking three copies of a^2: (a^2) · (a^2) · (a^2). "
        "By the product rule from Lecture 05, we add: 2 + 2 + 2 = 6, which is 2 times 3! "
        "So when a power is raised to another power, you MULTIPLY the exponents: a^(2 · 3) = a^6.\n"
        "Prof. Park: And when you have multiple factors inside parentheses raised to an outside power, like (2x^3)^4, "
        "the outside exponent distributes to EVERY single factor inside—including the numerical coefficient! "
        "So (2x^3)^4 = 2^4 · (x^3)^4 = 16 x^(3 · 4) = 16x^12.\n"
        "TA Sora: Never forget the coefficient! Students often write 2x^12, forgetting to raise 2 to the 4th power. "
        "Every citizen inside the parentheses gets hit by the outside exponent. Think of the outside exponent as rain falling on an open picnic table—everything on the table gets wet! "
        "Even in scientific notation, when you square (3 · 10^4)^2, you square 3 to get 9, and multiply exponents 4 · 2 = 8, giving 9 · 10^8. "
        "Treating every factor inside with equal respect guarantees no term is left unscaled."
    ),
    6: (
        "Prof. Park: Let's look at Example 5 Parts A and B on slide 6: "
        "Part A: (y^4)^5. "
        "Part B: (-2a^3)^4.\n"
        "TA Sora: In Part A, (y^4)^5 is a textbook power of a power. "
        "We multiply the inside exponent by the outside exponent: 4 · 5 = 20. "
        "So our result is y^20. Done in one clean step!\n"
        "Prof. Park: Now look at Part B: (-2a^3)^4. "
        "Here, the negative 2 is inside the parentheses, and the outside exponent is 4. "
        "We distribute the exponent 4 to both parts: "
        "First, (-2)^4. Since the exponent 4 is even, (-2)(-2)(-2)(-2) = +16. "
        "Second, (a^3)^4 = a^(3 · 4) = a^12. "
        "Combine them: +16a^12.\n"
        "TA Sora: Notice that an even power turns a negative coefficient positive: (-2)^4 = +16. "
        "If the outside power had been 3 (an odd power), (-2)^3 would have remained negative 8: -8a^9. "
        "And what if there were no parentheses: -2(a^3)^4? "
        "Then the 4 would only apply to a^3, giving -2a^12! "
        "Even powers absorb negatives inside parentheses; odd powers preserve them. Keep that rule in mind for rapid mental checking!"
    ),
    7: (
        "Prof. Park: Moving to slide 7 with Example 5 Parts C and D: "
        "Part C: (a^9 b^6)^5. "
        "Part D: (w^3 · w^8) / (w^5)^2.\n"
        "TA Sora: In Part C, (a^9 b^6)^5 has two variable factors inside. "
        "Distribute the outside exponent 5 to both: "
        "For a: (a^9)^5 = a^(9 · 5) = a^45. "
        "For b: (b^6)^5 = b^(6 · 5) = b^30. "
        "So our simplified term is a^45 b^30!\n"
        "Prof. Park: Now look at Part D: (w^3 · w^8) / (w^5)^2. "
        "Here we combine the product rule, the power of a power rule, and the quotient rule! "
        "Let's simplify top and bottom separately: "
        "In the numerator: w^3 · w^8 = w^(3 + 8) = w^11. "
        "In the denominator: (w^5)^2 = w^(5 · 2) = w^10.\n"
        "TA Sora: Now we have w^11 / w^10. "
        "Apply the quotient rule: 11 - 10 = 1. "
        "So w^11 / w^10 = w^1 = w! "
        "Look how an expression with four exponents collapsed down to a single letter w. That is mathematical elegance in action. "
        "If someone tested this with w = 2: numerator would be 2^3 · 2^8 = 8 · 256 = 2048. Denominator: (2^5)^2 = 32^2 = 1024. "
        "2048 divided by 1024 is exactly 2! The algebra works flawlessly with actual numbers."
    ),
    8: (
        "Prof. Park: Now let's tackle Example 5 Part E on slide 8: "
        "Simplify fully: [ (2 x^6 w^5) / (3 x w^5) ]^3.\n"
        "TA Sora: When you have a fraction inside parentheses raised to an outside power, you have two choices: "
        "Choice 1: Distribute the power 3 to every single factor on top and bottom first. "
        "Choice 2: SIMPLIFY INSIDE FIRST, then raise to the power 3! "
        "Sora's Golden Rule: ALWAYS simplify inside the parentheses first! It shrinks your numbers before you raise them to powers.\n"
        "Prof. Park: Let's follow Sora's advice and simplify inside first: "
        "Look at the w terms: w^5 on top and w^5 on the bottom. w^5 / w^5 = 1! They cancel out completely! "
        "Look at the x terms: x^6 on top and x^1 on the bottom. By the quotient rule: 6 - 1 = 5, so x^5 remains on top. "
        "The coefficients 2 and 3 cannot be reduced. "
        "So inside the parentheses, we are left with: (2x^5 / 3)!\n"
        "TA Sora: Look how much smaller that is! Now apply the outside cube 3 to everything: "
        "Numerator: 2^3 · (x^5)^3 = 8 x^(5 · 3) = 8x^15. "
        "Denominator: 3^3 = 27. "
        "Our final answer is: (8x^15) / 27. "
        "If we had distributed the cube first, we would have had 2^3 = 8, x^18, w^15 over 27 x^3 w^15, and then canceled. "
        "Simplifying inside first was much cleaner and saved us two full steps!"
    ),
    9: (
        "Prof. Park: Now we arrive at the ultimate master problem on slide 9: Example 5 Part F on workbook page 11: "
        "Simplify fully: [ (3 x^11 y^5) / (2 x^(-1) y^8) ]^(-2).\n"
        "TA Sora: This is the grand championship problem of Section 1.2! It has coefficients, positive exponents, negative exponents inside, and an outside negative exponent. "
        "Let's attack it methodically using our three-step protocol: "
        "Step 1: Simplify inside the parentheses first!\n"
        "Prof. Park: Let's do that! Look at x: we have x^11 on top and x^(-1) on the bottom. "
        "The x^(-1) on the bottom takes the elevator upstairs to the numerator and becomes x^(+1)! "
        "Upstairs, we already have x^11, so x^11 · x^1 = x^(11 + 1) = x^12. "
        "Now look at y: y^5 on top and y^8 on the bottom. "
        "8 - 5 = 3, so y^3 stays on the bottom. "
        "So inside our parentheses, we now have: (3 x^12) / (2 y^3).\n"
        "TA Sora: Step 2: Look at the outside exponent: it is -2! "
        "The negative sign on the outside exponent flips the entire inside fraction to its reciprocal: "
        "[ (2 y^3) / (3 x^12) ]^(+2)! "
        "Step 3: Now square every factor inside: "
        "Numerator: 2^2 · (y^3)^2 = 4 y^(3 · 2) = 4 y^6. "
        "Denominator: 3^2 · (x^12)^2 = 9 x^(12 · 2) = 9 x^24. "
        "Assemble the final fraction: (4 y^6) / (9 x^24)! "
        "Every exponent is positive, coefficients 4 and 9 share no common factors, and each variable appears once. Perfection!"
    ),
    10: (
        "Prof. Park: What a triumph! On slide 10, we synthesize all 5 examples from Section 1.2 into our Master Summary Table. "
        "Sora, let's review the final golden rules.\n"
        "TA Sora: 1. Zero Exponent: a^0 = 1 (for non-zero base). "
        "2. Product Rule: multiplying identical bases -> ADD exponents. "
        "3. Quotient Rule: dividing identical bases -> SUBTRACT exponents. "
        "4. Negative Exponents: the elevator rule—move across the fraction bar to turn positive. "
        "5. Power of a Power: multiply exponents. "
        "6. Power of a Fraction: simplify inside first, flip if the outside power is negative, then distribute to every factor.\n"
        "Prof. Park: Mastering these exponent laws is essential because they form the operational foundation for polynomial multiplication in Section 1.3, "
        "FOIL in Section 1.4, rational expressions in Section 1.5, and all factoring techniques in Unit 2. "
        "In Lecture 07, we advance to Section 1.3 on workbook page 12: Adding and Subtracting Polynomials. "
        "Outstanding work today, everyone, and we will see you in Lecture 07!"
    )
}

L07_TEXT = {
    1: (
        "Prof. Park: Welcome everyone to Lecture 07 of M090 Introductory Algebra! I am Professor Eunju Park, and joining me at the desk is TA Sora. "
        "Today, we open Section 1.3 of our course workbook, found on page 12: Adding and Subtracting Polynomials.\n"
        "TA Sora: Hello everyone! Today we transition from working with single-term monomials to working with polynomials—expressions that contain multiple terms combined by addition and subtraction. "
        "In the real world, polynomials are the mathematical models behind everything from cost and revenue curves in business, "
        "to trajectory curves of aircraft landing at Bozeman Yellowstone International Airport, to stress loads on construction framing in Gallatin Valley residential builds. "
        "For example, a business in Belgrade might model its total revenue as R(x) = 150x - 0.5x^2, and its production costs as C(x) = 3000 + 40x. "
        "To find profit, they subtract the cost polynomial from the revenue polynomial: P(x) = R(x) - C(x)! "
        "Understanding how to classify, add, subtract, and distribute polynomials is the foundational engine of business, engineering, and data science.\n"
        "Prof. Park: Let's review the essential vocabulary on slide 1: "
        "A monomial has exactly 1 term (like 5x^3). "
        "A binomial has exactly 2 terms (like 2x + 7). "
        "A trinomial has exactly 3 terms (like 4x^2 - 5x + 9). "
        "And any algebraic expression composed of one or more terms is a polynomial. "
        "Each term consists of a numerical coefficient and variable factors. "
        "The degree of a single term is the sum of the exponents on its variables: for instance, 4x^3 has degree 3, while 7x^2 y^4 has degree 2 + 4 = 6! "
        "The degree of an entire polynomial is the highest degree of any term present. "
        "Sora, what is the golden requirement for combining terms in a polynomial?\n"
        "TA Sora: LIKE TERMS ONLY! Two terms are 'like terms' if and only if they have the exact same variable raised to the exact same exponent! "
        "For example, 5x^2 and 3x^2 are like terms because both have x squared. But 5x^2 and 5x are NOT like terms because one has power 2 and the other has power 1. "
        "When you combine like terms, you add or subtract the numerical coefficients, and the variable part remains completely unchanged. Let's practice on slide 2!"
    ),
    2: (
        "Prof. Park: Let's examine Section 1.3 Examples 1A and 1B on workbook page 12: "
        "Part A: Simplify 6y + 12 - 7y. "
        "Part B: Simplify -3x^2 + 5x + 9x^2 - 2.\n"
        "TA Sora: In Part A, we have three terms: 6y, +12, and -7y. "
        "Let's identify the like terms: 6y and -7y both have the variable y to the first power. The constant 12 is on its own. "
        "Combine the like terms by adding their numerical coefficients: 6 - 7 = -1. "
        "So 6y - 7y = -1y, which in algebra we write simply as -y. "
        "Now bring along the constant +12: our simplified expression is -y + 12 (or 12 - y). "
        "Notice how the variable y didn't change at all—it did not become y squared, and it did not disappear. "
        "Only the count of how many y's we have changed from 6 and -7 to -1.\n"
        "Prof. Park: Now look at Part B: -3x^2 + 5x + 9x^2 - 2. "
        "Here we have terms of degree 2, degree 1, and degree 0 (the constant). "
        "Let's group the degree 2 terms: -3x^2 and +9x^2. "
        "Combine their coefficients: -3 + 9 = +6, so we have 6x^2. "
        "Now look for other degree 1 terms: we have +5x, but no other x terms to combine with, so it stays +5x. "
        "And the constant -2 is alone, so it stays -2. "
        "Assembling in descending order of exponents gives: 6x^2 + 5x - 2.\n"
        "TA Sora: Why do we write it in descending order? "
        "Writing polynomials in descending degree order—highest power first, down to the constant—is standard mathematical etiquette. "
        "It makes it easy to identify the leading coefficient, which is 6, the degree of the polynomial, which is 2 (a quadratic trinomial), "
        "and ensures everyone grading your paper can immediately confirm your answer. "
        "You can also align them in vertical columns on your paper: place degree 2 terms in one column, degree 1 in the next, and constants at the end, just like multi-digit addition in grade school!"
    ),
    3: (
        "Prof. Park: Moving to slide 3, let's tackle Examples 1C and 1D: "
        "Part C: 3n^2 - 17n - n^2 + 4n. "
        "Part D: 4ab^2 + 6a^2 b - 8ab^2 + 2a^2 b.\n"
        "TA Sora: In Part C, notice the term -n^2. "
        "Whenever a variable appears with a negative sign but no written number in front, its invisible coefficient is 1! So -n^2 is really -1n^2. "
        "Always write that little '1' with your pencil if you are prone to skipping it. "
        "Now let's group the n^2 terms: 3n^2 - 1n^2 = (3 - 1)n^2 = 2n^2. "
        "Next, group the linear n terms: -17n + 4n = (-17 + 4)n = -13n. "
        "Combine them: 2n^2 - 13n. "
        "Students often ask: 'Can I combine 2n^2 - 13n into -11n?' Absolutely not! "
        "n^2 and n are completely different dimensions—one is an area of size n by n, and the other is a length of size n. They cannot be combined!\n"
        "Prof. Park: Now look at Part D—this is a classic exam trap: "
        "4ab^2 + 6a^2 b - 8ab^2 + 2a^2 b. "
        "Sora, both terms contain a and b, so why aren't all four of them like terms?\n"
        "TA Sora: Because the exponents on the individual variables are different! "
        "In 4ab^2, the b is squared: a^1 b^2. "
        "In 6a^2 b, the a is squared: a^2 b^1. "
        "Think of construction materials: ab^2 is a board of width a and length b squared, while a^2 b is a board of width a squared and length b! "
        "They have different geometric shapes and cannot be stacked together. "
        "Let's combine matching categories: "
        "For the ab^2 group: 4ab^2 - 8ab^2 = (4 - 8)ab^2 = -4ab^2. "
        "For the a^2 b group: 6a^2 b + 2a^2 b = (6 + 2)a^2 b = +8a^2 b. "
        "Our final answer is: -4ab^2 + 8a^2 b (or 8a^2 b - 4ab^2). Always match the exponent to the specific letter!"
    ),
    4: (
        "Prof. Park: Slide 4 takes us to Example 2 Parts A and B on page 12: Adding and Subtracting Polynomial Groups: "
        "Part A: (5x^3 + 2x^2 - 13x) + (4x^3 - 8x^2 + 2x). "
        "Part B: (7x^2 - 5x + 3) - (2x^2 - 9x - 6).\n"
        "TA Sora: In Part A, we are ADDING two polynomial groups. "
        "When there is an addition sign (+) between the parentheses, the parentheses serve only as containers and can simply be removed without altering any signs! "
        "Let's remove the parentheses and group like terms: "
        "Cubic terms: 5x^3 + 4x^3 = 9x^3. "
        "Quadratic terms: 2x^2 - 8x^2 = -6x^2. "
        "Linear terms: -13x + 2x = -11x. "
        "Our resulting polynomial is: 9x^3 - 6x^2 - 11x.\n"
        "Prof. Park: But in Part B, we have SUBTRACTION: (7x^2 - 5x + 3) - (2x^2 - 9x - 6). "
        "Sora, what is the single biggest trap on algebra exams with polynomial subtraction?\n"
        "TA Sora: Students only subtract the very first term, 2x^2, and leave the other terms untouched! "
        "That minus sign sitting outside the second parentheses acts as a multiplier of negative 1: -1 · (2x^2 - 9x - 6). "
        "It MUST distribute to EVERY single term inside that second set of parentheses! "
        "Watch what happens to the signs: "
        "- (2x^2) becomes -2x^2. "
        "- (-9x) becomes +9x! The negative times negative becomes positive! "
        "- (-6) becomes +6! The negative times negative becomes positive!\n"
        "Prof. Park: Rewrite the entire line without parentheses: "
        "7x^2 - 5x + 3 - 2x^2 + 9x + 6. "
        "Now combine like terms: "
        "7x^2 - 2x^2 = 5x^2. "
        "-5x + 9x = +4x. "
        "+3 + 6 = +9. "
        "Our final simplified result is: 5x^2 + 4x + 9! "
        "Distributing that negative sign across all three terms is the secret to 100% accuracy on subtraction problems. "
        "If you have time, you can even check your answer by adding the result (5x^2 + 4x + 9) back to the subtracted group (2x^2 - 9x - 6) to verify it yields the original (7x^2 - 5x + 3)!"
    ),
    5: (
        "Prof. Park: Now let's explore the Distributive Property with Monomials on slide 5: Examples 3A and 3B on workbook page 13: "
        "Part A: -2x(3x^2 + 8x - 4). "
        "Part B: 4x^2(2x^3 - 5x + 7).\n"
        "TA Sora: The Distributive Property says: a(b + c + d) = ab + ac + ad. "
        "The monomial sitting outside multiplies every single term inside the parentheses! "
        "Think of a physical rectangular field in Gallatin County partitioned into three sections: "
        "the common width is -2x, and the three lengths are 3x^2, 8x, and -4. "
        "The total area is the sum of the three individual section areas! "
        "And remember: when multiplying variable terms, we use the product rule from Lecture 05—we MULTIPLY the coefficients and we ADD the exponents!\n"
        "Prof. Park: Let's distribute -2x to each of the three terms in Part A: "
        "First term: (-2x)(3x^2). Multiply coefficients: -2 · 3 = -6. Add exponents: x^1 · x^2 = x^3. Result: -6x^3. "
        "Second term: (-2x)(8x). Multiply coefficients: -2 · 8 = -16. Add exponents: x^1 · x^1 = x^2. Result: -16x^2. "
        "Third term: (-2x)(-4). Negative times negative is positive! (-2)(-4) = +8, with x attached: +8x.\n"
        "TA Sora: Assemble the three products: -6x^3 - 16x^2 + 8x. "
        "Notice the signs flipped completely: positive 3x^2 became negative, positive 8x became negative, and negative 4 became positive! "
        "Now let's do Part B: 4x^2(2x^3 - 5x + 7). "
        "Term 1: (4x^2)(2x^3) = (4 · 2) x^(2 + 3) = 8x^5. "
        "Term 2: (4x^2)(-5x^1) = (4 · -5) x^(2 + 1) = -20x^3. "
        "Term 3: (4x^2)(7) = (4 · 7) x^2 = +28x^2. "
        "Combine them: 8x^5 - 20x^3 + 28x^2. "
        "Notice that there are no like terms among x^5, x^3, and x^2, so this polynomial is fully simplified."
    ),
    6: (
        "Prof. Park: Moving to slide 6, let's examine Examples 3C and 3D: "
        "Part C: -x(x^2 - 4) - 2(x^3 + 2x - 5). "
        "Part D: 3x^2(x - 4) + 2x(x^2 - 5x + 1).\n"
        "TA Sora: In Part C, we have TWO separate distributive blocks separated by subtraction: "
        "Block 1: -x(x^2 - 4). Distribute -x: (-x)(x^2) = -x^3, and (-x)(-4) = +4x. "
        "Block 2: -2(x^3 + 2x - 5). Distribute -2: (-2)(x^3) = -2x^3, (-2)(2x) = -4x, and (-2)(-5) = +10.\n"
        "Prof. Park: Now write all terms in a single line and combine like terms: "
        "-x^3 + 4x - 2x^3 - 4x + 10. "
        "Cubic terms: -1x^3 - 2x^3 = -3x^3. "
        "Linear terms: +4x - 4x = 0x! They cancel each other out completely! "
        "Constant: +10. "
        "So our simplified result is simply: -3x^3 + 10!\n"
        "TA Sora: Now let's conquer Part D: 3x^2(x - 4) + 2x(x^2 - 5x + 1). "
        "Distribute the first block: 3x^2(x) - 3x^2(4) = 3x^3 - 12x^2. "
        "Distribute the second block: 2x(x^2) - 2x(5x) + 2x(1) = 2x^3 - 10x^2 + 2x. "
        "Now combine like terms: "
        "Cubic terms: 3x^3 + 2x^3 = 5x^3. "
        "Quadratic terms: -12x^2 - 10x^2 = -22x^2. "
        "Linear term: +2x. "
        "Final polynomial: 5x^3 - 22x^2 + 2x. Modularity makes even long problems simple."
    ),
    7: (
        "Prof. Park: To conclude Lecture 07, let's look at slide 7: Nested Grouping Symbols—Examples 3E and 3F: "
        "Part E: 3 + 2[ 5x - 4(x - 9) ] + 7. "
        "Sora, when grouping symbols are nested inside brackets, how do we proceed?\n"
        "TA Sora: Work strictly from the INSIDE OUT! "
        "Always locate the innermost parentheses first. "
        "Here, the innermost part is -4(x - 9). "
        "Distribute -4: (-4)(x) = -4x, and (-4)(-9) = +36. "
        "Now look inside the brackets: [ 5x - 4x + 36 ]. "
        "Combine like terms inside the brackets: 5x - 4x = x. So the brackets collapse to [ x + 36 ]!\n"
        "Prof. Park: Look how clean that is! Now our expression is: 3 + 2[ x + 36 ] + 7. "
        "Next, distribute the outside 2 into the brackets: "
        "2(x) = 2x, and 2(36) = 72. "
        "Now our full line is: 3 + 2x + 72 + 7. "
        "Now simply combine all the constants: 3 + 72 = 75, plus 7 = 82! "
        "So our final simplified answer is: 2x + 82.\n"
        "TA Sora: Look at how an intimidating problem with brackets, parentheses, and four operations collapsed into a simple two-term binomial: 2x + 82! "
        "When students try to rush and distribute from the outside in, they create enormous fractions and sign errors. "
        "Working from the inside out guarantees clarity at every step. "
        "In Lecture 08, we advance to Section 1.4: Multiplying Polynomials and the FOIL Method on workbook page 14. "
        "Practice combining like terms tonight, and we will see you in Lecture 08!"
    )
}

L08_TEXT = {
    1: (
        "Prof. Park: Welcome everyone to Lecture 08 of M090 Introductory Algebra! I am Professor Eunju Park, and joining me is TA Sora. "
        "Today, we explore Section 1.4 of our course workbook, spanning pages 14 and 15: Multiplying Polynomials and the FOIL Strategy.\n"
        "TA Sora: Hello everyone! Today we learn how to multiply binomials and polynomials together. "
        "This is one of the most famous and heavily used procedures in all of secondary and college mathematics. "
        "Whether you are finding the area of a newly planned building footprint in Bozeman, calculating economic revenue functions (price times quantity) for a business in Belgrade, "
        "or factoring quadratic equations in Unit 2, polynomial multiplication is the universal engine behind it all.\n"
        "Prof. Park: That is right, Sora. When we multiply two binomials—like (a + b)(c + d)—every term in the first binomial must multiply every term in the second binomial. "
        "To help students remember all four multiplications without missing any, educators developed the famous acronym: FOIL! "
        "F stands for First terms. "
        "O stands for Outer terms. "
        "I stands for Inner terms. "
        "L stands for Last terms.\n"
        "TA Sora: You can also think of FOIL geometrically as an area model or a 2-by-2 Punnett square: "
        "draw a rectangle partitioned into 4 smaller cells. The top sides are a and b, and the left sides are c and d. "
        "The areas of the four cells are ac, ad, bc, and bd! When you sum the cells together, you get the exact same result. "
        "Visual learners in architectural drafting and carpentry often love the box model, while algebraic thinkers love the rhythmic flow of FOIL. "
        "Let's examine how the FOIL strategy works on slide 2 with Example 1!"
    ),
    2: (
        "Prof. Park: Let's examine Section 1.4 Examples 1A and 1B on workbook page 14: "
        "Part A: (2x + 4)(3x + 5). "
        "Part B: (x - 6)(x + 8).\n"
        "TA Sora: Let's execute FOIL step by step on Part A: (2x + 4)(3x + 5): "
        "F - First terms: multiply the first terms of each binomial: (2x)(3x) = 6x^2. "
        "O - Outer terms: multiply the terms on the far outside: (2x)(5) = +10x. "
        "I - Inner terms: multiply the terms on the inside: (4)(3x) = +12x. "
        "L - Last terms: multiply the last terms of each binomial: (4)(5) = +20.\n"
        "Prof. Park: Now write all four products in a line: 6x^2 + 10x + 12x + 20. "
        "Notice that the two middle terms—the Outer and Inner terms—are like terms! Both have x to the first power. "
        "10x + 12x = 22x. "
        "Combining them gives our final trinomial: 6x^2 + 22x + 20!\n"
        "TA Sora: Now let's tackle Part B: (x - 6)(x + 8). "
        "Watch your signs carefully here! "
        "F - First: (x)(x) = x^2. "
        "O - Outer: (x)(8) = +8x. "
        "I - Inner: (-6)(x) = -6x. "
        "L - Last: (-6)(8) = -48. "
        "Combine the middle like terms: +8x - 6x = +2x. "
        "Our final trinomial is: x^2 + 2x - 48. "
        "Notice the predictable rhythm: First gives the quadratic term, Outer and Inner combine to give the linear term, and Last gives the constant. "
        "If you do this 5 times, your hand will automatically glide through FOIL without even pausing to think."
    ),
    3: (
        "Prof. Park: Now look at slide 3 with Examples 1C and 1D: Binomial Products with Leading Constants: "
        "Part C: 2(b - 3)(b + 4). "
        "Part D: -3(2y - 1)(3y + 4).\n"
        "TA Sora: In Part C, we have three factors: the constant 2, and two binomials (b - 3) and (b + 4). "
        "Students often ask: 'Should I distribute the 2 first, or FOIL the binomials first?' "
        "And more dangerously, some students distribute the 2 to BOTH binomials—writing (2b - 6)(2b + 8)! "
        "That is completely wrong—that would be multiplying by 4, not 2! Multiplication is associative, so 2 multiplies only once.\n"
        "Prof. Park: That is such a vital distinction, Sora. "
        "Sora's Golden Tip is: FOIL the binomials first, keep them inside protective parentheses, and distribute the leading constant at the very end! "
        "Let's follow that advice for Part C: "
        "FOIL (b - 3)(b + 4): "
        "First: b · b = b^2. "
        "Outer: b · 4 = +4b. "
        "Inner: -3 · b = -3b. "
        "Last: -3 · 4 = -12. "
        "Combine middle terms: 4b - 3b = +b. "
        "So the binomial product is (b^2 + b - 12). "
        "Now multiply the entire trinomial by the leading 2: "
        "2(b^2 + b - 12) = 2b^2 + 2b - 24!\n"
        "TA Sora: Look how effortless that was! Now look at Part D: -3(2y - 1)(3y + 4). "
        "FOIL the binomials first: "
        "First: (2y)(3y) = 6y^2. "
        "Outer: (2y)(4) = +8y. "
        "Inner: (-1)(3y) = -3y. "
        "Last: (-1)(4) = -4. "
        "Combine middle terms: 8y - 3y = +5y, giving (6y^2 + 5y - 4). "
        "Now distribute the leading -3: "
        "(-3)(6y^2) = -18y^2. "
        "(-3)(+5y) = -15y. "
        "(-3)(-4) = +12. "
        "Final result: -18y^2 - 15y + 12. Methodical execution produces effortless accuracy."
    ),
    4: (
        "Prof. Park: Slide 4 highlights the single most notorious trap in introductory algebra: Squaring a Binomial! "
        "Part E: (2y - 7)^2. "
        "Part F: 2(y - 7)^2. "
        "Sora, sound the alarm!\n"
        "TA Sora: MAXIMUM ALERT LEVEL! (2y - 7)^2 does NOT equal (2y)^2 - 7^2! "
        "Students who distribute the exponent 2 get 4y^2 - 49 or 4y^2 + 49, and they lose all points on the problem! "
        "Exponents do NOT distribute across addition or subtraction! "
        "Think geometrically: if you have a square of side (a + b), its area is (a + b)^2. "
        "That large square contains a square of size a^2, a square of size b^2, AND two large rectangles of size a · b! "
        "If you write a^2 + b^2, you threw away both rectangles! That is like buying a house and forgetting the living room!\n"
        "Prof. Park: That is a wonderful mental visual! "
        "Squaring a binomial means multiplying that entire binomial by ITSELF! "
        "Whenever you see (2y - 7)^2, immediately write it as two side-by-side parentheses: (2y - 7)(2y - 7)! "
        "Now FOIL: "
        "First: (2y)(2y) = 4y^2. "
        "Outer: (2y)(-7) = -14y. "
        "Inner: (-7)(2y) = -14y. "
        "Last: (-7)(-7) = +49. "
        "Now look at the middle terms: -14y and -14y do NOT cancel! They ADD: -14y - 14y = -28y! "
        "So (2y - 7)^2 = 4y^2 - 28y + 49. The middle term -28y is essential!\n"
        "TA Sora: And look at Part F: 2(y - 7)^2. "
        "First write (y - 7)^2 as (y - 7)(y - 7). "
        "FOIL gives: y^2 - 7y - 7y + 49 = y^2 - 14y + 49. "
        "Now distribute the leading 2: 2(y^2 - 14y + 49) = 2y^2 - 28y + 98. "
        "Write out both binomials every time, and you will never drop the middle term."
    ),
    5: (
        "Prof. Park: Let's expand our horizons on slide 5 with Examples 1H and 1I: Multiplying Binomials by Trinomials: "
        "Part H: (w + 2)(w^2 - 2w + 9). "
        "Part I: (2x - 3)(x^2 + 4x - 5).\n"
        "TA Sora: When multiplying a 2-term binomial by a 3-term trinomial, FOIL expands into the generalized distributive property: "
        "Each of the 2 terms in the first group must multiply each of the 3 terms in the second group. "
        "2 times 3 equals 6 total multiplications!\n"
        "Prof. Park: Let's do Part H systematically: "
        "First, distribute w to all three terms: "
        "w(w^2) = w^3. "
        "w(-2w) = -2w^2. "
        "w(9) = +9w. "
        "Next, distribute +2 to all three terms: "
        "2(w^2) = +2w^2. "
        "2(-2w) = -4w. "
        "2(9) = +18.\n"
        "TA Sora: Now align like terms: "
        "w^3 is alone. "
        "Quadratic terms: -2w^2 + 2w^2 = 0w^2! They cancel completely! "
        "Linear terms: +9w - 4w = +5w. "
        "Constant: +18. "
        "Our final result is: w^3 + 5w + 18!\n"
        "Prof. Park: Now let's tackle Part I: (2x - 3)(x^2 + 4x - 5). "
        "Distribute 2x to all three terms: "
        "(2x)(x^2) = 2x^3. "
        "(2x)(4x) = +8x^2. "
        "(2x)(-5) = -10x. "
        "Now distribute -3 to all three terms: "
        "(-3)(x^2) = -3x^2. "
        "(-3)(4x) = -12x. "
        "(-3)(-5) = +15.\n"
        "TA Sora: Now combine like terms: "
        "Cubic: 2x^3. "
        "Quadratic: 8x^2 - 3x^2 = +5x^2. "
        "Linear: -10x - 12x = -22x. "
        "Constant: +15. "
        "Final polynomial: 2x^3 + 5x^2 - 22x + 15! Six multiplications combined into four clean terms."
    ),
    6: (
        "Prof. Park: Moving to slide 6, let's examine Examples 2 and 3: Real-World Geometry Applications on workbook page 15. "
        "A rectangle has length L = 3x - 4 and width W = 2x + 1. "
        "Example 2 asks for the Perimeter. Example 3 asks for the Area.\n"
        "TA Sora: This is where algebra directly connects to physical space and cost estimating! "
        "In Gallatin County construction, if a general contractor is installing baseboard trim around the room, they need the Perimeter. "
        "If they are ordering hardwood flooring planks, they need the Area! "
        "For Perimeter, the distance all the way around a rectangle is: P = 2L + 2W. "
        "Substitute our algebraic expressions: P = 2(3x - 4) + 2(2x + 1). "
        "Distribute: 2(3x) - 2(4) = 6x - 8. "
        "And 2(2x) + 2(1) = 4x + 2. "
        "Combine like terms: 6x + 4x = 10x, and -8 + 2 = -6. "
        "So Perimeter P = 10x - 6 linear units!\n"
        "Prof. Park: Now Example 3 asks for the Area. The area of a rectangle is length times width: A = L · W. "
        "So we must multiply the two binomials: A = (3x - 4)(2x + 1)! "
        "This is a job for FOIL: "
        "First: (3x)(2x) = 6x^2. "
        "Outer: (3x)(1) = +3x. "
        "Inner: (-4)(2x) = -8x. "
        "Last: (-4)(1) = -4. "
        "Combine middle terms: 3x - 8x = -5x. "
        "So Area A = 6x^2 - 5x - 4 square units!\n"
        "TA Sora: Notice the clear distinction: Perimeter is an addition problem of degree 1 (10x - 6), "
        "while Area is a multiplication problem of degree 2 (6x^2 - 5x - 4). The mathematical degree matches the physical dimensions!"
    ),
    7: (
        "Prof. Park: To conclude Lecture 08, let's examine Example 4 on slide 7: Modified Rectangle Dimensions on workbook page 15. "
        "A given rectangle has length 2x + 3 and width x - 6. "
        "If the length is increased by 4 and the width is decreased by 2, find the simplified polynomial expression for the new area.\n"
        "TA Sora: Let's adjust the dimensions first: "
        "Original Length = 2x + 3. Increased by 4: (2x + 3) + 4 = 2x + 7. "
        "Original Width = x - 6. Decreased by 2: (x - 6) - 2 = x - 8. "
        "Now our new dimensions are Length = 2x + 7 and Width = x - 8!\n"
        "Prof. Park: Now find the new area by multiplying the modified binomials: "
        "Area = (2x + 7)(x - 8). "
        "Execute FOIL: "
        "First: (2x)(x) = 2x^2. "
        "Outer: (2x)(-8) = -16x. "
        "Inner: (7)(x) = +7x. "
        "Last: (7)(-8) = -56. "
        "Combine the middle like terms: -16x + 7x = -9x. "
        "Our new area is: 2x^2 - 9x - 56 square units!\n"
        "TA Sora: Let's do a quick reality check: suppose x = 10 feet. "
        "Original dimensions would be 2(10)+3 = 23 ft by 10-6 = 4 ft, area = 92 sq ft. "
        "New dimensions: 2(10)+7 = 27 ft by 10-8 = 2 ft, area = 54 sq ft. "
        "Now test our algebraic formula: 2(10)^2 - 9(10) - 56 = 2(100) - 90 - 56 = 200 - 146 = 54 sq ft! "
        "It matches with 100% precision. "
        "In Lecture 09, we transition to Section 1.5 on workbook page 16: Adding and Subtracting Rational Expressions. "
        "We will apply our fraction arithmetic from Lecture 01 to algebraic fractions with variables in the denominators. "
        "Fantastic work today, everyone, and we will see you in Lecture 09!"
    )
}

L09_TEXT = {
    1: (
        "Prof. Park: Welcome everyone to Lecture 09 of M090 Introductory Algebra! I am Professor Eunju Park, and joining me at the teaching desk is TA Sora. "
        "Today, we launch into Section 1.5 of our course workbook, found on page 16: Adding and Subtracting Rational Expressions.\n"
        "TA Sora: Hello everyone! Today represents a major milestone in your algebra journey. "
        "We are taking the fraction arithmetic skills we mastered back in Lectures 01 and 02 and merging them with the variable polynomials we have studied all week. "
        "A rational expression is simply a fraction where the numerator and denominator are polynomials—like 5 over w, or 3 over x squared. "
        "Students are often intimidated when variables appear downstairs in the denominator, but the fundamental law of fractions NEVER changes: "
        "to add or subtract pieces, they must share a common denominator!\n"
        "Prof. Park: That is the universal principle: A/C + B/C = (A + B)/C, and A/C - B/C = (A - B)/C. "
        "If the denominators already match, you simply add or subtract the numerators and keep the common denominator. "
        "Think of physical units in everyday Montana life: imagine agricultural irrigation ditches in the Gallatin Valley. "
        "If you have one canal pumping 3 cubic feet of water per second through a diversion gate of capacity C, "
        "and a second canal feeding 2 cubic feet per second through that same gate capacity C, the combined flow rate is (3 + 2) = 5 cubic feet per second over that identical gate capacity C! "
        "You never add the gate capacities together to get 2C! You only add the amounts of water flowing through them.\n"
        "TA Sora: Exactly! But if the denominators are different—like one pump measured in cubic feet per second and another in gallons per minute—you cannot combine them directly. "
        "You must find the Least Common Denominator, or LCD. "
        "Finding the LCD for algebraic expressions follows a simple, foolproof two-step strategy that works every single time: "
        "Step 1: Find the numerical LCD for the integer coefficients using standard times tables. For example, for 6 and 4, the numerical LCD is 12. "
        "Step 2: For each variable that appears in any denominator, take that variable raised to its HIGHEST exponent present in any single denominator! "
        "For instance, if one denominator has x and another has x cubed, the LCD must contain x cubed. "
        "Once you have the LCD, you scale each fraction by multiplying top and bottom by whatever factors are missing, combine the numerators over the common denominator, "
        "and reduce to lowest terms. Let's see this in action on slide 2!"
    ),
    2: (
        "Prof. Park: Slide 2 presents Section 1.5 Examples 1A and 1B on workbook page 16: "
        "Part A: Find the sum 1/6 + 3/4. "
        "Part B: Find the sum 2/x + 5/x.\n"
        "TA Sora: Let's start with Part A: 1/6 + 3/4. This reviews our numerical fraction foundation from Lecture 01. "
        "The denominators are 6 and 4. Multiples of 6 are 6, 12, 18... and multiples of 4 are 4, 8, 12... "
        "The Least Common Denominator is 12! "
        "Now build equivalent fractions by multiplying by 1 in disguise: "
        "For 1/6, multiply top and bottom by 2/2: (1 · 2) / (6 · 2) = 2/12. "
        "For 3/4, multiply top and bottom by 3/3: (3 · 3) / (4 · 3) = 9/12. "
        "Now that the denominators are identical, combine numerators: 2/12 + 9/12 = (2 + 9)/12 = 11/12! "
        "11 is prime, so 11/12 is in simplest form.\n"
        "Prof. Park: Now look at Part B right next to it: 2/x + 5/x. "
        "Notice what happened: the numerical denominators 6 and 4 were replaced by the variable x! "
        "Sora, how do students react when they see this?\n"
        "TA Sora: Many students freeze because of the letter x, but look closely: the denominators ALREADY MATCH! "
        "Both fractions have the exact same denominator, x. "
        "Therefore, no scaling is needed! We simply add the numerators directly over the shared denominator: "
        "(2 + 5) / x = 7/x! "
        "That is all there is to it: 7/x.\n"
        "Prof. Park: Let's highlight a very common mistake here: some students write 7 / 2x, mistakenly adding x + x in the denominator! "
        "Sora, remind everyone why that is mathematically impossible.\n"
        "TA Sora: The denominator tells you the size of the container! "
        "If you have 2 fifths of an apple and you add 5 fifths of an apple, you have 7 fifths—you do not have 7 tenths! "
        "In 1/12 + 9/12, the denominator stayed 12—it didn't become 24. "
        "In the exact same way, 2/x + 5/x stays over x, giving 7/x. Denominators never add together when combining fractions."
    ),
    3: (
        "Prof. Park: Now let's advance to slide 3 with Examples 2A and 2B on page 16: Monomial Common Denominators: "
        "Part A: 5/w - 7/w^2. "
        "Part B: 3/x + 4/y.\n"
        "TA Sora: Let's dissect Part A: 5/w - 7/w^2. "
        "Here the denominators are different: one is w, and the other is w^2! "
        "Remember our golden rule for variable LCDs: take each variable to its HIGHEST power present in any denominator! "
        "The powers of w are w^1 and w^2. The highest power is w^2, so our LCD is w^2!\n"
        "Prof. Park: Exactly. Notice that the second fraction, 7/w^2, already has the complete LCD. It needs no modification at all! "
        "The first fraction is 5/w. What factor is missing from its denominator to make it w^2? It is missing a single factor of w! "
        "So we multiply top and bottom by w/w: (5 · w) / (w · w) = 5w / w^2.\n"
        "TA Sora: Now both fractions share the common denominator w^2! "
        "Subtract the numerators: (5w - 7) / w^2. "
        "Can we simplify 5w - 7 any further? 5w and -7 are unlike terms, so they cannot be combined. "
        "And can we cancel the w in 5w with the w^2 in the denominator? ABSOLUTELY NOT!\n"
        "Prof. Park: That is one of the most critical warnings in the entire course! "
        "Why can't we cancel that w, Sora?\n"
        "TA Sora: Because addition and subtraction act as industrial cement! "
        "5w is glued to -7 by subtraction. You can only cancel common FACTORS that multiply an entire numerator, never individual TERMS inside a sum or difference! "
        "Unless you can factor a w out of both 5w and -7, you cannot touch it. "
        "So (5w - 7) / w^2 is our final, fully simplified answer.\n"
        "Prof. Park: Now look at Part B: 3/x + 4/y. "
        "Here we have two completely different variables in the denominators: x and y! "
        "Since they share no common factors, our LCD is simply their product: xy. "
        "Scale the first fraction by y/y: (3 · y) / (x · y) = 3y / xy. "
        "Scale the second fraction by x/x: (4 · x) / (y · x) = 4x / xy. "
        "Now combine numerators over the common denominator: (3y + 4x) / xy (or (4x + 3y) / xy). "
        "Clean, elegant, and fully simplified!"
    ),
    4: (
        "Prof. Park: Let's move to slide 4 with Examples 2C and 2D: Two-Variable Denominators: "
        "Part C: 3/y + 5/(2y). "
        "Part D: 4/(3a) - 1/(2a).\n"
        "TA Sora: Let's analyze Part C: 3/y + 5/(2y). "
        "Look at the denominators: y and 2y. "
        "Numerically, we have coefficients 1 and 2, so the numerical LCD is 2. "
        "For the variable part, both have y to the first power, so the variable LCD is y. "
        "Combining them gives our Least Common Denominator: 2y!\n"
        "Prof. Park: Notice that the second fraction 5/(2y) already has the denominator 2y. "
        "The first fraction is 3/y, which is missing a factor of 2. "
        "So we scale 3/y by multiplying top and bottom by 2/2: (3 · 2) / (y · 2) = 6 / (2y). "
        "Now add the numerators: 6/(2y) + 5/(2y) = (6 + 5) / (2y) = 11 / (2y)! "
        "11 is prime and shares no factors with 2, so 11/(2y) is our final answer.\n"
        "TA Sora: Now let's tackle Part D: 4/(3a) - 1/(2a). "
        "Look at the denominators: 3a and 2a. "
        "Let's break this into our two modular steps: "
        "Step 1: The numerical coefficients are 3 and 2. Multiples of 3 are 3, 6, 9... and multiples of 2 are 2, 4, 6... "
        "The numerical LCD is 6! "
        "Step 2: Both denominators contain the variable a to the first power, so the variable part is simply a. "
        "Combining them gives an LCD of 6a!\n"
        "Prof. Park: Now let's build our equivalent fractions: "
        "To turn 3a into 6a, we need to multiply by 2. So multiply top and bottom by 2/2: (4 · 2) / (3a · 2) = 8 / (6a). "
        "To turn 2a into 6a, we need to multiply by 3. So multiply top and bottom by 3/3: (1 · 3) / (2a · 3) = 3 / (6a). "
        "Now subtract the numerators: (8 - 3) / (6a) = 5 / (6a)! "
        "5 and 6 share no common factors, so 5/(6a) is in lowest terms. "
        "Notice how treating the numbers and the variables as separate modular components makes finding the LCD completely stress-free."
    ),
    5: (
        "Prof. Park: To conclude Lecture 09, let's examine slide 5 with Examples 2E and 2F: Mixed Constant and Variable Denominators: "
        "Part E: 2/(7r) + 3/(14r). "
        "Part F: 5/(6k^2) - 1/(4k).\n"
        "TA Sora: In Part E, look at the denominators: 7r and 14r. "
        "Notice that 14 is a direct multiple of 7 (7 · 2 = 14)! "
        "And both have r to the first power. "
        "Therefore, our LCD is simply 14r! The second fraction 3/(14r) stays unchanged. "
        "We only need to scale the first fraction: multiply top and bottom by 2/2: "
        "(2 · 2) / (7r · 2) = 4 / (14r). "
        "Now add: 4/(14r) + 3/(14r) = (4 + 3) / (14r) = 7 / (14r).\n"
        "Prof. Park: But wait! Look at our result: 7 / (14r). Are we finished? "
        "TA Sora: Absolutely not! Always inspect your final fraction for reduction opportunities! "
        "7 on top and 14 on the bottom both divide by 7! "
        "7 divided by 7 is 1. 14 divided by 7 is 2. "
        "So 7/(14r) reduces cleanly to 1 / (2r)! "
        "Remember: the 1 in the numerator is mandatory. You cannot write 2r—the 2r is in the denominator, so it must be 1/(2r).\n"
        "Prof. Park: Now let's conquer Part F: 5/(6k^2) - 1/(4k). "
        "This is our grand finale for Lecture 09! "
        "Coefficients: 6 and 4. Multiples of 6 are 6, 12... multiples of 4 are 4, 8, 12... The numerical LCD is 12! "
        "Variables: k^2 and k^1. The highest power is k^2. "
        "So our total LCD is 12k^2!\n"
        "TA Sora: Let's scale both fractions to 12k^2: "
        "For 5/(6k^2), multiply top and bottom by 2/2: (5 · 2) / (6k^2 · 2) = 10 / (12k^2). "
        "For 1/(4k), to turn 4k into 12k^2, we must multiply by 3k! "
        "Multiply top and bottom by 3k / 3k: (1 · 3k) / (4k · 3k) = 3k / (12k^2). "
        "Now subtract the numerators: (10 - 3k) / (12k^2). "
        "Can we reduce 10 - 3k over 12k^2? No, 10 and 3k share no common factor, so nothing can be factored out. "
        "Our final answer is: (10 - 3k) / (12k^2)!\n"
        "Prof. Park: In Lecture 10, we continue Section 1.5 with advanced rational expressions: higher powers, three-term sums, and binomial numerators. See you all in Lecture 10!"
    )
}

L10_TEXT = {
    1: (
        "Prof. Park: Welcome everyone to Lecture 10 of M090 Introductory Algebra! I am Professor Eunju Park, and joining me at the teaching desk is TA Sora. "
        "Today, we take our rational expression skills to the master level in Section 1.5 Part 2, found on workbook page 17: "
        "Advanced Rational Addition and Subtraction.\n"
        "TA Sora: Hello everyone! Today's lecture addresses the problems that students find most challenging in Unit 1: "
        "expressions with higher-degree variable denominators like x^4, three fractions added together simultaneously, "
        "and fractions with entire binomials in their numerators. "
        "When an entire binomial is in a numerator, subtracting fractions requires distributing a negative sign across multiple terms. "
        "If you master today's six examples, you will be completely prepared for every rational expression on your exams.\n"
        "Prof. Park: That is right, Sora. In engineering and physical science, compound rate equations—like calculating the equivalent electrical resistance of multiple parallel circuits, 1/R = 1/R1 + 1/R2 + 1/R3, "
        "or computing shared work rates when multiple construction crews pave Montana highways—rely directly on combining three or more rational terms. "
        "For instance, if Crew A takes x hours to pave a section of Highway 191 near Big Sky, and Crew B takes 2x hours, their combined hourly paving rate is 1/x + 1/(2x) = 3/(2x)! "
        "Let's look at slide 2 to begin with Example 3A!"
    ),
    2: (
        "Prof. Park: Slide 2 presents Section 1.5 Example 3A on workbook page 17: "
        "Add and simplify: 3 / (7x^2) + 5 / (14x).\n"
        "TA Sora: Let's find our Least Common Denominator systematically: "
        "Look at the numerical coefficients: 7 and 14. 14 is a multiple of 7, so our numerical LCD is 14. "
        "Look at the variable powers: x^2 and x^1. The highest power is x^2. "
        "Combine them: our LCD is 14x^2!\n"
        "Prof. Park: Now let's check what each fraction needs: "
        "The first fraction is 3 / (7x^2). Its denominator already has x^2, but needs its coefficient scaled from 7 to 14. "
        "So we multiply top and bottom by 2/2: (3 · 2) / (7x^2 · 2) = 6 / (14x^2). "
        "The second fraction is 5 / (14x). Its coefficient is already 14, but it only has x to the first power. It needs one more x to reach x^2! "
        "So we multiply top and bottom by x/x: (5 · x) / (14x · x) = 5x / (14x^2).\n"
        "TA Sora: Now both fractions share the identical denominator 14x^2. "
        "Combine the numerators: 6/(14x^2) + 5x/(14x^2) = (6 + 5x) / (14x^2), which we write in standard order as (5x + 6) / (14x^2). "
        "Can we cancel x in 5x with x^2 on the bottom? Never! 5x is part of the sum (5x + 6). "
        "Unless the entire binomial has a common factor with the denominator, no canceling is allowed. (5x + 6) / (14x^2) is our final answer!"
    ),
    3: (
        "Prof. Park: Let's elevate the challenge with Example 3B on slide 3: a three-term rational expression with a 4th power: "
        "Simplify: 2/x - 9 / (10x^4) + 3 / (5x^2).\n"
        "TA Sora: Three fractions at once! Don't let the length intimidate you—our LCD strategy works identically regardless of how many fractions there are. "
        "Look at the denominators: x, 10x^4, and 5x^2. "
        "Step 1: Numerical coefficients are 1, 10, and 5. Multiples of 10 and 5 give a numerical LCD of 10! "
        "Step 2: Variable powers are x^1, x^4, and x^2. The highest exponent present is 4! "
        "So our variable LCD is x^4. "
        "Combining them gives our overall Least Common Denominator: 10x^4!\n"
        "Prof. Park: Now let's scale each of the three fractions into equivalent fractions with denominator 10x^4: "
        "Fraction 1: 2/x. To turn x into 10x^4, multiply by 10x^3: (2 · 10x^3) / (x · 10x^3) = 20x^3 / (10x^4). "
        "Fraction 2: 9 / (10x^4). Its denominator is already 10x^4! It needs no scaling at all. "
        "Fraction 3: 3 / (5x^2). To turn 5x^2 into 10x^4, multiply by 2x^2: (3 · 2x^2) / (5x^2 · 2x^2) = 6x^2 / (10x^4).\n"
        "TA Sora: Now combine all three numerators over the common denominator 10x^4, paying close attention to the operations: "
        "The first operation is subtraction, and the second is addition: "
        "(20x^3 - 9 + 6x^2) / (10x^4). "
        "Rearrange the numerator terms in descending degree order: (20x^3 + 6x^2 - 9) / (10x^4). "
        "None of the numerator terms can be combined because their degrees are 3, 2, and 0. "
        "And 20, 6, and -9 share no common factor with 10. Our three-term rational expression is fully simplified!"
    ),
    4: (
        "Prof. Park: Moving to slide 4, let's examine Examples 3C and 3D: Multi-Term Common Denominators: "
        "Part C: 2 / (3b) + 1/4 + 1 / (6b). "
        "Sora, walk us through finding the LCD when one term is a pure constant fraction without a variable!\n"
        "TA Sora: That is a wonderful detail to notice! "
        "The denominators are 3b, 4, and 6b. "
        "First, look at the numbers: 3, 4, and 6. "
        "Multiples of 6 are 6, 12, 18... 12 is divisible by 3, 4, and 6! So our numerical LCD is 12. "
        "Second, look at the variable: b appears to the first power in two denominators. Even though the middle fraction 1/4 has no b, "
        "any fraction in the family that needs b must receive b! So our variable LCD is b. "
        "Combining them gives an LCD of 12b!\n"
        "Prof. Park: Let's scale all three fractions to 12b: "
        "Fraction 1: 2 / (3b). Multiply top and bottom by 4/4: (2 · 4) / (3b · 4) = 8 / (12b). "
        "Fraction 2: 1/4. To turn 4 into 12b, we must multiply by 3b! "
        "Multiply top and bottom by 3b / 3b: (1 · 3b) / (4 · 3b) = 3b / (12b). "
        "Fraction 3: 1 / (6b). Multiply top and bottom by 2/2: (1 · 2) / (6b · 2) = 2 / (12b).\n"
        "TA Sora: Now combine the numerators over 12b: "
        "8 + 3b + 2 = (3b + 10) / (12b). "
        "Can we reduce 3b + 10 over 12b? "
        "Look at 3, 10, and 12: 3 and 12 share 3, but 10 is not divisible by 3. 10 and 12 share 2, but 3 is not divisible by 2. "
        "There is NO common factor shared by all terms. "
        "Therefore, (3b + 10) / (12b) is in lowest terms!"
    ),
    5: (
        "Prof. Park: Now we arrive at slide 5, which features the single most critical problem type in Section 1.5: "
        "Example 3E: Subtracting Fractions with Binomial Numerators: "
        "(2x - 5) / (3x) - (5x + 9) / (6x).\n"
        "TA Sora: Sound the emergency siren! This is where hundreds of algebra students lose points on Exam 1! "
        "Why? Because of that minus sign between the fractions! "
        "When you subtract a fraction whose numerator is a binomial, that minus sign MUST distribute to EVERY term in the numerator! "
        "Sora's Golden Rule: Immediately wrap every binomial numerator in protective parentheses before you do anything else: "
        "[ (2x - 5) ] / (3x) - [ (5x + 9) ] / (6x)!\n"
        "Prof. Park: Let's find the LCD first. The denominators are 3x and 6x. "
        "6 is a multiple of 3, and both have x to the first power. So our Least Common Denominator is 6x! "
        "The second fraction already has 6x. "
        "For the first fraction, we must multiply top and bottom by 2/2: "
        "2 · (2x - 5) / (3x · 2) = (4x - 10) / (6x).\n"
        "TA Sora: Now place both numerators over the common denominator 6x: "
        "[ (4x - 10) - (5x + 9) ] / (6x). "
        "Look at that second set of parentheses: - (5x + 9). "
        "Distribute the minus sign: -5x - 9! "
        "So our numerator becomes: 4x - 10 - 5x - 9. "
        "Now combine like terms: 4x - 5x = -x. "
        "And -10 - 9 = -19! "
        "So our numerator is -x - 19. "
        "Over the common denominator 6x, our final answer is: (-x - 19) / (6x) (or - (x + 19) / (6x)). "
        "If a student failed to distribute the negative, they would get -10 + 9 = -1, which is completely wrong. Protective parentheses save the day!"
    ),
    6: (
        "Prof. Park: To conclude Lecture 10, let's look at slide 6: Example 3F on workbook page 17—our Second Binomial Subtraction Master Problem: "
        "(3y + 7) / (8y) - (9y - 11) / (4y).\n"
        "TA Sora: Let's apply our bulletproof procedure: "
        "Step 1: Wrap the binomial numerators in protective parentheses: [ (3y + 7) ] / (8y) - [ (9y - 11) ] / (4y). "
        "Step 2: Find the LCD. The denominators are 8y and 4y. 8 is a multiple of 4, so our LCD is 8y! "
        "Step 3: Scale the second fraction. To turn 4y into 8y, multiply top and bottom by 2/2: "
        "2 · (9y - 11) / (4y · 2) = (18y - 22) / (8y).\n"
        "Prof. Park: Now write over the single common denominator 8y: "
        "[ (3y + 7) - (18y - 22) ] / (8y). "
        "Distribute the negative sign to the second numerator: "
        "- (18y - 22) becomes -18y + 22! Notice that -(-22) became POSITIVE 22!\n"
        "TA Sora: That double negative turning into +22 is where the magic happens! "
        "Now combine like terms in the numerator: "
        "3y - 18y = -15y. "
        "+7 + 22 = +29! "
        "So our numerator is -15y + 29 (or 29 - 15y). "
        "Over the common denominator 8y, our final simplified answer is: (-15y + 29) / (8y)! "
        "Can we cancel the y in 15y with the y in 8y? No! -15y is tied to 29 by addition. No canceling is possible.\n"
        "Prof. Park: That brings us to the conclusion of Lecture 10 and the complete mastery of Section 1.5! "
        "In Lecture 11, we will begin Section 1.6 on workbook page 18: Solving Linear Equations. "
        "Outstanding job everyone, and we will see you in Lecture 11!"
    )
}

# Write out unit1_scripts_l06_l08.py
with open('Montana_State_Univ/scripts/unit1_scripts_l06_l08.py', 'w', encoding='utf-8') as f:
    f.write('# -*- coding: utf-8 -*-\n')
    f.write('"""\nunit1_scripts_l06_l08.py\nHigh-volume 20-25 minute broadcast tiki-taka scripts for Lectures 06, 07, and 08.\n"""\n\n')
    f.write('SCRIPTS_L06 = ' + json.dumps(L06_TEXT, indent=4, ensure_ascii=False) + '\n\n')
    f.write('SCRIPTS_L07 = ' + json.dumps(L07_TEXT, indent=4, ensure_ascii=False) + '\n\n')
    f.write('SCRIPTS_L08 = ' + json.dumps(L08_TEXT, indent=4, ensure_ascii=False) + '\n')

# Write out unit1_scripts_l09_l10.py
with open('Montana_State_Univ/scripts/unit1_scripts_l09_l10.py', 'w', encoding='utf-8') as f:
    f.write('# -*- coding: utf-8 -*-\n')
    f.write('"""\nunit1_scripts_l09_l10.py\nHigh-volume 20-25 minute broadcast tiki-taka scripts for Lectures 09 and 10.\n"""\n\n')
    f.write('SCRIPTS_L09 = ' + json.dumps(L09_TEXT, indent=4, ensure_ascii=False) + '\n\n')
    f.write('SCRIPTS_L10 = ' + json.dumps(L10_TEXT, indent=4, ensure_ascii=False) + '\n')

print("Batch 2 scripts successfully generated.")
