# -*- coding: utf-8 -*-
"""
unit1_scripts_l04_l05.py
High-volume 20-25 minute broadcast tiki-taka scripts for Lectures 04 and 05.
Prof. Eunju Park & TA Sora.
Target: ~2,400-2,650 words per lecture (~240-280 words per slide).
"""

SCRIPTS_L04 = {
    1: (
        "Prof. Park: Welcome everyone to Lecture 04 of M090 Introductory Algebra! I am Professor Eunju Park, and joining me at the teaching desk is TA Sora. "
        "Today, we explore one of the most critical bridge skills between human thought and mathematical power: Section 1.1 on workbook page 7, "
        "Translating English Phrases into Algebraic Expressions.\n"
        "TA Sora: Hello everyone! If you ask college students across the country what makes word problems difficult, 99% of the time they say: "
        "'I know how to do the math once I have the equation, but I don't know how to set it up!' "
        "Setting up word problems is not a mysterious art—it is simply bilingual translation. "
        "English is a rich, descriptive language, while algebra is an ultra-precise, compact symbolic language. "
        "Today, we are going to build your personal translation dictionary so you can convert any English description into an exact algebraic expression effortlessly.\n"
        "Prof. Park: That is exactly right, Sora. In real life across Montana—whether estimating construction lumber costs in Gallatin Valley, "
        "calculating seed and fertilizer ratios for wheat farming in Chouteau County, computing hiking trail ascent rates in the Bridger Range, "
        "or budgeting travel fuel along Interstate 90—real problems never arrive as ready-made equations printed on paper. "
        "They arrive in spoken English conversations! "
        "Let's look at slide 2 to uncover the foundational signal words for the four basic operations and the famous reversal rule."
    ),
    2: (
        "Prof. Park: On slide 2, we organize the English vocabulary of mathematics into the Big 4 operations: addition, subtraction, multiplication, and division. "
        "Notice how certain words directly dictate operations.\n"
        "TA Sora: For Addition, our signal words include: 'sum', 'plus', 'increased by', 'more than', 'added to', and 'total'. "
        "For Multiplication, look for: 'product', 'times', 'multiplied by', 'twice' (which means multiply by 2), 'triple', and the subtle word 'of'—as in 'three-fourths OF a number'. "
        "For Division, our keywords are: 'quotient', 'divided by', 'ratio of', and 'per'—like miles per hour or cost per gallon.\n"
        "Prof. Park: But Subtraction requires our highest alert level! Words like 'difference', 'minus', and 'decreased by' maintain standard left-to-right order: "
        "'10 minus x' translates directly to 10 - x. "
        "However, Sora, what happens when students hear 'less than' or 'subtracted from'?\n"
        "TA Sora: RED ALERT! 'Less than' and 'subtracted from' are ORDER-REVERSAL words! "
        "If I say: '5 less than 20', think about what that means in real life: you start with 20 dollars, and you have 5 dollars less than that, so 20 - 5 = 15. "
        "The 20 comes FIRST, and the 5 comes LAST! "
        "So '5 less than a number y' is y - 5, NEVER 5 - y. "
        "5 - y would mean you have 5 dollars and spend y dollars. "
        "Notice that English syntax places the modifier first, but algebraic logic places the starting quantity first. "
        "Whenever you hear 'less than' or 'subtracted from', draw a reverse arrow over your paper!"
    ),
    3: (
        "Prof. Park: Let's apply this immediately to Workbook Phrases #1 and #2 on slide 3: "
        "Phrase #1: 'The sum of 8 and a number x'. "
        "Phrase #2: '5 less than a number y'.\n"
        "TA Sora: Let's dissect Phrase #1: 'The sum of 8 and a number x'. "
        "The keyword is 'sum', which signals addition (+). "
        "The two quantities being joined are 8 and x. "
        "So we write 8 + x. Since addition is commutative, x + 8 has the exact same numerical value, but 8 + x preserves the natural English flow.\n"
        "Prof. Park: Now look at Phrase #2: '5 less than a number y'. "
        "Here is our order-reversal trap word: 'less than'! "
        "Sora, walk us through the mental check.\n"
        "TA Sora: As soon as your eyes see 'less than', circle it with your pencil and draw a reverse arrow underneath! "
        "You are starting with 'a number y', and you are taking 5 away from it. "
        "Therefore, the algebraic translation is y - 5. "
        "If you write 5 - y, you have inverted the subtraction. "
        "Think of a paycheck: if you earn y dollars and have 5 dollars deducted for parking, your take-home pay is y - 5. "
        "If you wrote 5 - y, you would have a negative paycheck! Subtraction is NOT commutative—order matters completely. y - 5 is our only correct answer."
    ),
    4: (
        "Prof. Park: Moving to slide 4, let's examine Workbook Phrases #3 and #4: "
        "Phrase #3: 'The quotient of a number z and 7'. "
        "Phrase #4: '4 times the sum of a number and 9'.\n"
        "TA Sora: In Phrase #3, the keyword is 'quotient', which signals division. "
        "In English grammar, 'the quotient of A and B' always means A divided by B, where A is the numerator and B is the denominator. "
        "Here, A is 'a number z' and B is 7. "
        "So we write z / 7, or z over 7 as a vertical fraction. "
        "In college algebra, we always write quotients as vertical fractions rather than using the old grade-school division symbol ÷. "
        "A fraction bar naturally packages the numerator and denominator into clear algebraic units.\n"
        "Prof. Park: Now look at Phrase #4: '4 times the sum of a number and 9'. "
        "Notice the grouping requirement! We are NOT multiplying 4 just by the number. We are multiplying 4 times THE SUM of a number and 9!\n"
        "TA Sora: Exactly! 'The sum of a number n and 9' is (n + 9). "
        "Because 4 multiplies the entire sum, we MUST wrap that sum in protective parentheses: 4(n + 9). "
        "Think of calculating the perimeter of a garden: if you have length plus width, and you double it, you write 2(l + w). "
        "If a student forgets the parentheses and writes 4n + 9, they have translated '9 more than 4 times a number'. "
        "Whenever an operation applies to a sum or difference, parentheses are mandatory. 4(n + 9) is the exact translation!"
    ),
    5: (
        "Prof. Park: Let's advance to slide 5 with Phrases #5 and #6: "
        "Phrase #5: 'The square of the sum of a and b'. "
        "Phrase #6: '12 decreased by twice a number w'.\n"
        "TA Sora: Look closely at Phrase #5: 'The square OF the sum of a and b'. "
        "Notice the order of words: 'the square of...' comes first, which means the squaring exponent applies to whatever comes next. "
        "And what comes next? 'The sum of a and b', which is (a + b). "
        "So we wrap (a + b) in parentheses and raise the whole package to the second power: (a + b)^2!\n"
        "Prof. Park: Contrast that with 'the sum of the squares of a and b', which would be a^2 + b^2. "
        "Those two expressions are completely different—geometrically, (a + b)^2 represents the total area of a large square of side (a + b), "
        "which expands to a^2 + 2ab + b^2! In contrast, a^2 + b^2 is missing the two middle rectangles 2ab. Word order is everything.\n"
        "TA Sora: Now let's tackle Phrase #6: '12 decreased by twice a number w'. "
        "We begin with the constant 12. "
        "'Decreased by' signals standard subtraction (-). It does NOT reverse the order like 'less than' does. "
        "And what are we subtracting? 'Twice a number w', which means 2 times w, or 2w. "
        "So we write: 12 - 2w. Clean, direct, and in exact sequential order: 12 - 2w."
    ),
    6: (
        "Prof. Park: Let's inspect Phrases #7 and #8 on slide 6: "
        "Phrase #7: 'The cube of a number c increased by 10'. "
        "Phrase #8: 'The product of -6 and the square of x'.\n"
        "TA Sora: In Phrase #7, 'the cube of a number c' means c raised to the third power: c^3. "
        "Then we have 'increased by 10', which is addition of 10. "
        "So we combine them into: c^3 + 10. "
        "Notice that only c is cubed, not the 10, because 'increased by 10' comes after the cube. "
        "If it had said 'the cube of the sum of c and 10', it would be (c + 10)^3. Always track which word controls the exponent!\n"
        "Prof. Park: Now look at Phrase #8: 'The product of -6 and the square of x'. "
        "'Product' means multiplication between two factors. "
        "The first factor is -6. "
        "The second factor is 'the square of x', which is x^2. "
        "So we multiply -6 by x^2, giving -6x^2. "
        "In physics, formulas like -16t^2 for gravitational falling distance use this exact structure: a coefficient multiplied by a squared variable."
    ),
    7: (
        "Prof. Park: Moving to slide 7 with Phrases #9 and #10: "
        "Phrase #9: 'Three-fifths of a number m'. "
        "Phrase #10: 'The difference of twice x and three times y'.\n"
        "TA Sora: In Phrase #9, the phrase 'three-fifths OF a number m' uses the critical word 'of'. "
        "When 'of' follows a fraction, decimal, or percentage, it almost always signals multiplication! "
        "Think of baking in a kitchen: if a recipe calls for three-fifths of a cup of flour, you multiply 3/5 by the total amount. "
        "Three-fifths is the fraction 3/5. "
        "Multiplying by m gives: (3/5)m, which can also be written as a single fraction: 3m / 5. "
        "Both (3/5)m and 3m/5 are completely equivalent and accepted on all homework and exams.\n"
        "Prof. Park: Now let's examine Phrase #10: 'The difference of twice x and three times y'. "
        "'Difference' signals subtraction between two parts. "
        "The first part is 'twice x', which is 2x. "
        "The second part is 'three times y', which is 3y. "
        "Because it says 'difference OF A and B', it maintains standard left-to-right order: A - B. "
        "So our algebraic translation is simply: 2x - 3y.\n"
        "TA Sora: Professor Park, let's address a frequent student question here: students often ask, 'Can I combine 2x - 3y into -1xy?' "
        "The answer is an emphatic NO! 2x and 3y are UNLIKE terms. "
        "They represent entirely different categories of items—like 2 elk and 3 bison in Yellowstone! "
        "You cannot subtract bison from elk to get a hybrid animal. You simply leave them as 2x - 3y."
    ),
    8: (
        "Prof. Park: Let's tackle Phrases #11 and #12 on slide 8: "
        "Phrase #11: '8 subtracted from the quotient of p and 4'. "
        "Phrase #12: 'The sum of 15 and half of a number k'.\n"
        "TA Sora: Look at Phrase #11: '8 subtracted FROM the quotient of p and 4'. "
        "There is our order-reversal keyword again: 'SUBTRACTED FROM'! "
        "If I take 8 dollars away from your wallet, your wallet had the money first. "
        "So 'the quotient of p and 4'—which is p/4—comes FIRST! "
        "And the 8 is subtracted at the end: (p/4) - 8. "
        "If you wrote 8 - (p/4), you fell into the reversal trap. Remember: 'subtracted from' always puts that number at the very back: (p/4) - 8!\n"
        "Prof. Park: Perfect explanation. And notice the difference between '(p/4) - 8' and '(p - 8)/4'. "
        "If the English had said 'the quotient of 8 less than p and 4', the subtraction would be inside the numerator. "
        "Here, 8 is subtracted from the entire quotient, so the -8 sits outside the fraction!\n"
        "TA Sora: Now Phrase #12: 'The sum of 15 and half of a number k'. "
        "'Sum' means addition (+). "
        "The first part is 15. "
        "The second part is 'half of a number k', which is (1/2)k, or k/2. "
        "So we write: 15 + (1/2)k, or 15 + k/2. Both are 100% correct!"
    ),
    9: (
        "Prof. Park: Slide 9 presents our final two translation challenges from the table: Phrases #13 and #14: "
        "Phrase #13: 'The absolute value of the difference between x and 9'. "
        "Phrase #14: 'The square of the difference of 6 and m'.\n"
        "TA Sora: In Phrase #13, 'the absolute value of...' tells us that everything that follows must be enclosed inside vertical absolute value bars: | ... |. "
        "Inside the bars, we have 'the difference between x and 9', which is x - 9. "
        "So we write: | x - 9 |. "
        "This expression models real-world engineering tolerance! If a machine part must be manufactured within a fraction of a millimeter of 9 mm, "
        "the error |x - 9| measures the physical distance from the target.\n"
        "Prof. Park: And look at Phrase #14: 'The square of the difference of 6 and m'. "
        "Just like Phrase #5 earlier, 'the square of...' means the exponent 2 will apply to an entire grouped quantity. "
        "The quantity is 'the difference of 6 and m', which is 6 - m. "
        "So we wrap (6 - m) in parentheses and square it: (6 - m)^2. "
        "Notice that 6 comes first, because 'difference of 6 and m' maintains standard order: (6 - m)^2."
    ),
    10: (
        "Prof. Park: To wrap up Lecture 04, let's look at slide 10: Reverse Translation—turning algebraic expressions back into English words! "
        "Look at the drills from the bottom of workbook page 7: "
        "1. 6a^3 + 13 "
        "2. 5b^2 - 8\n"
        "TA Sora: Let's translate 6a^3 + 13 into English. "
        "We can say: '13 more than the product of 6 and the cube of a'. "
        "Or we can say: 'The sum of 6 times the cube of a and 13'. "
        "Both describe the exact same algebraic structure!\n"
        "Prof. Park: And for 5b^2 - 8: "
        "We can say: '8 less than 5 times the square of b'. "
        "Or: 'The difference of 5 times the square of b and 8'. "
        "Notice how using 'less than' tests your mastery of the reversal rule in reverse! "
        "Being able to travel fluently in both directions—from English to algebra, and from algebra to English—proves that you truly understand the meaning of mathematical symbols.\n"
        "TA Sora: In Lecture 05, we dive into Section 1.2 on workbook page 8: Simplifying Monomial Expressions with Exponents! "
        "We will master the zero exponent rule, the product rule, and the quotient rule. "
        "Fantastic work today, everyone, and we will see you in Lecture 05!"
    )
}

SCRIPTS_L05 = {
    1: (
        "Prof. Park: Welcome everyone to Lecture 05 of M090 Introductory Algebra! I am Professor Eunju Park, and with me at the teaching desk is TA Sora. "
        "Today, we launch into Section 1.2 of our course workbook, spanning pages 8 through 10: "
        "Simplifying Monomial Expressions with Exponents.\n"
        "TA Sora: Hello everyone! Today is all about understanding how exponents behave when we multiply, divide, and scale monomial terms. "
        "A monomial is simply an algebraic expression with a single term—like 5x^3, or -2a^4 b^2. "
        "Exponents appear everywhere in modern science and technology: from computer memory measured in binary powers (kilobytes, megabytes, gigabytes as powers of 2), "
        "to modeling bacterial cultures in microbiology labs at Montana State, to calculating earthquake magnitudes on the Richter scale.\n"
        "Prof. Park: Many students try to memorize exponent rules as disconnected formulas, and then panic on exams about when to add exponents versus when to multiply or subtract them. "
        "Today, Sora and I will show you the simple, physical logic behind every single rule so that you never have to guess. "
        "Open your workbooks to page 8, and let's examine the three fundamental properties on slide 2!"
    ),
    2: (
        "Prof. Park: On slide 2, we have the three core exponent properties covered in Part 1 of Section 1.2: "
        "1. The Zero Exponent Rule: a^0 = 1 (for any non-zero base a). "
        "2. The Product Rule: a^m · a^n = a^(m+n). "
        "3. The Quotient Rule: a^m / a^n = a^(m-n) (where a is non-zero).\n"
        "TA Sora: Let's make sure everyone understands WHY these rules work! "
        "Take the Product Rule: a^2 · a^3. "
        "What does a^2 mean? It means (a · a). "
        "What does a^3 mean? It means (a · a · a). "
        "When you multiply them together, you have: (a · a) · (a · a · a). "
        "How many copies of a are multiplied in total? Five copies! Which is a^5. "
        "Notice what happened: 2 + 3 = 5! When multiplying identical bases, you ADD the exponents.\n"
        "Prof. Park: And now look at the Quotient Rule: a^5 / a^2. "
        "On top, we have five copies: (a · a · a · a · a). "
        "On the bottom, we have two copies: (a · a). "
        "Two copies on top cancel with the two copies on the bottom, leaving three copies on top: a^(5 - 2) = a^3! "
        "So when dividing identical bases, you SUBTRACT the bottom exponent from the top exponent.\n"
        "TA Sora: And look at what happens if you divide a^3 by a^3: "
        "By the quotient rule, a^(3 - 3) = a^0. "
        "But any non-zero quantity divided by itself equals 1! "
        "Therefore, a^0 MUST equal 1! It is not an arbitrary rule; it is an unavoidable logical necessity.\n"
        "Prof. Park: And notice that critical condition in the textbook: 'for any non-zero base a'. "
        "Why can't the base a be zero? Because 0^0 leads to a direct mathematical conflict between 0 raised to any power being 0, "
        "and any base raised to the power 0 being 1! In higher mathematics, 0^0 is an indeterminate form. "
        "For all non-zero real numbers, a^0 is unconditionally 1. Let's practice with Example 1!"
    ),
    3: (
        "Prof. Park: Slide 3 takes us to Section 1.2 Example 1 on workbook page 8: "
        "Simplify each expression as much as possible: "
        "Part A: t^0. "
        "Part B: (-5)^0. "
        "Part C: -5^0. "
        "Part D: (4x)^0 versus 4x^0.\n"
        "TA Sora: Part A: t^0. Any non-zero variable raised to the power of 0 equals 1! So t^0 = 1. Simple and clean.\n"
        "Prof. Park: Now look at Part B and Part C—this brings back our base-identification lesson from Lecture 02! "
        "Part B is (-5)^0. The negative 5 is inside parentheses. "
        "That means the ENTIRE quantity -5 is the base being raised to the power 0. "
        "Any non-zero base to the 0 power equals 1, so (-5)^0 = +1!\n"
        "TA Sora: But look at Part C: -5^0 without parentheses! "
        "Here, the exponent 0 only touches the number 5 directly to its left! "
        "5^0 is 1. The negative sign is a multiplier of -1 sitting out in front. "
        "So -5^0 = -(5^0) = -1! "
        "Compare Parts B and C side by side: (-5)^0 is +1, but -5^0 is -1! That distinction will definitely appear on your exam.\n"
        "Prof. Park: And look at Part D: (4x)^0 versus 4x^0. "
        "In (4x)^0, the parentheses group both 4 and x, so the entire group to the 0 power equals 1. "
        "In 4x^0, the exponent 0 applies ONLY to x! So x^0 becomes 1, and 4 times 1 is 4! "
        "Parentheses control the boundary of the base every single time."
    ),
    4: (
        "Prof. Park: Let's move to slide 4 with Example 2 Parts A and B on page 9: "
        "Part A: a^2 · a^5. "
        "Part B: (3x^4)(5x^6).\n"
        "TA Sora: Part A is a direct application of the Product Rule: a^2 · a^5. "
        "Both terms have the identical base, a. "
        "So we keep the base a and add the exponents: 2 + 5 = 7. "
        "Our answer is simply a^7. "
        "A common student mistake is to multiply the exponents and write a^10. Remember: you only multiply exponents when a power is raised to another power, like (a^2)^5. Here, we are multiplying bases, so we ADD: a^7!\n"
        "Prof. Park: Now look at Part B: (3x^4)(5x^6). "
        "Here we have both numerical coefficients (3 and 5) and variable terms with exponents (x^4 and x^6). "
        "Sora, how do we organize our work here?\n"
        "TA Sora: Group like elements together! Use the commutative property of multiplication to rearrange: "
        "Put the coefficients together: (3 · 5). "
        "Put the variable terms together: (x^4 · x^6). "
        "Now treat them separately: "
        "3 times 5 is ordinary arithmetic: 15. "
        "For x^4 · x^6, we use the product rule: add exponents 4 + 6 = 10, giving x^10. "
        "Combine them: 15x^10! "
        "Never add the coefficients—3 and 5 are multiplied to get 15. Only the exponents on matching bases are added."
    ),
    5: (
        "Prof. Park: Let's expand this technique on slide 5 with Example 2 Parts C and D: "
        "Part C: (2xy^2)(3xy^3). "
        "Part D: (-4a^3 b)(2a^5 b^4).\n"
        "TA Sora: In Part C, look at each variable carefully: (2xy^2)(3xy^3). "
        "Notice that x has no written exponent! "
        "When a variable appears without an exponent, its invisible exponent is 1: x is really x^1! "
        "Always write that little '1' with your pencil so you don't forget to count it.\n"
        "Prof. Park: That is such a vital tip! Let's group our factors: "
        "Coefficients: 2 · 3 = 6. "
        "For the x terms: x^1 · x^1 = x^(1+1) = x^2. "
        "For the y terms: y^2 · y^3 = y^(2+3) = y^5. "
        "Assembling our monomial gives: 6x^2 y^5. Clean and complete!\n"
        "TA Sora: Now let's conquer Part D: (-4a^3 b)(2a^5 b^4). "
        "First, the single b has an invisible exponent of 1: b^1. "
        "Multiply the coefficients: (-4) · (2) = -8. "
        "Combine the a bases: a^3 · a^5 = a^(3+5) = a^8. "
        "Combine the b bases: b^1 · b^4 = b^(1+4) = b^5. "
        "Our final product is: -8a^8 b^5. "
        "Notice how systematic this is: signs and coefficients first, then variable a, then variable b. Modularity prevents mistakes."
    ),
    6: (
        "Prof. Park: Now let's shift to the Quotient Rule on slide 6 with Example 3 Part A on workbook page 9: "
        "Fully simplify using only positive integer exponents: r^11 / r^4.\n"
        "TA Sora: We have identical bases, r, in a fraction. "
        "The Quotient Rule tells us: keep the base r, and subtract the denominator exponent from the numerator exponent: "
        "11 - 4 = 7. "
        "So r^11 / r^4 = r^7!\n"
        "Prof. Park: Let's visualize that physically: imagine 11 copies of r multiplied in a row on the numerator, and 4 copies of r on the denominator. "
        "Four of the r's on the bottom cancel four of the r's on top. "
        "How many are left? Exactly 7 copies of r, sitting comfortably in the numerator: r^7.\n"
        "TA Sora: Exactly. And because the result is in the numerator with an exponent of positive 7, no negative exponents are involved. "
        "Always ask yourself: 'Where were there more factors to begin with?' "
        "There were 11 on top and 4 on the bottom, so there are 7 extra factors on top. That physical picture will keep you grounded."
    ),
    7: (
        "Prof. Park: Let's elevate the challenge with Example 3 Part B on slide 7: "
        "Fully simplify: (2m^2 / 5n^3) · (10n^5 / 4m).\n"
        "TA Sora: Here we have two monomial fractions multiplied together. "
        "We could multiply straight across and simplify at the end, but remember TA Sora's golden rule from Lecture 02: "
        "ALWAYS PRE-CANCEL whenever possible!\n"
        "Prof. Park: Let's inspect the numbers and variables across the diagonals: "
        "Look at the coefficients: 2 in the top left and 4 in the bottom right. Divide both by 2: 2 becomes 1, and 4 becomes 2. "
        "Look at 10 in the top right and 5 in the bottom left. Divide both by 5: 10 becomes 2, and 5 becomes 1. "
        "Now look at the remaining numbers: we have 2 on top and 2 on the bottom! They cancel completely: 2/2 = 1!\n"
        "TA Sora: The numbers completely canceled down to 1! That is amazing. "
        "Now look at the variables: "
        "We have m^2 on top and m^1 on the bottom: m^(2 - 1) = m^1, which leaves m on top. "
        "We have n^5 on top and n^3 on the bottom: n^(5 - 3) = n^2 on top. "
        "Multiplying what is left gives: m · n^2 in the numerator, and 1 in the denominator. "
        "So our final simplified answer is simply: m n^2! "
        "Pre-canceling transformed a messy expression into an elegant two-variable product in seconds."
    ),
    8: (
        "Prof. Park: Now look at Example 3 Part C on slide 8: "
        "Fully simplify: (2m^2 / 5n^3) ÷ (10n^5 / 4m). "
        "Notice the problem looks almost identical to Part B, BUT the operation between the fractions is DIVISION, not multiplication!\n"
        "TA Sora: What a fantastic comparison! When dividing fractions, our very first move is: Keep, Change, Flip! "
        "Keep the first fraction: 2m^2 / 5n^3. "
        "Change division to multiplication: ·. "
        "Flip the second fraction to its reciprocal: 4m / 10n^5! "
        "Our problem becomes: (2m^2 / 5n^3) · (4m / 10n^5).\n"
        "Prof. Park: Notice that flipping changed the entire layout! "
        "Now the 4m is on top, and 10n^5 is on the bottom. "
        "Let's look at the numbers: 2 on top and 10 on the bottom reduce by 2: 2 becomes 1, and 10 becomes 5. "
        "In the numerator, we have 1 · 4 = 4. "
        "In the denominator, we have 5 · 5 = 25.\n"
        "TA Sora: Now look at the variables: "
        "In the numerator: m^2 · m^1 = m^3. "
        "In the denominator: n^3 · n^5 = n^(3+5) = n^8! "
        "Notice that the m's are BOTH in the numerator, so their exponents ADD! "
        "The n's are BOTH in the denominator, so their exponents ADD! "
        "Our final fraction is: 4m^3 / (25n^8). "
        "Compare Part B and Part C: changing multiplication to division flipped the second term and completely changed the final outcome. Always check the operational sign first!"
    ),
    9: (
        "Prof. Park: Let's examine our grand finale for this section: Example 3 Part D on slide 9: "
        "Fully simplify: (8x^9 y^8 z^5) / (12x^4 y^12 z^0).\n"
        "TA Sora: This is a multi-variable monomial quotient. Let's attack it modularly, one piece at a time! "
        "First, look at z^0 in the denominator: by the zero exponent rule, z^0 = 1! "
        "So z^0 simply equals 1 and disappears from the denominator.\n"
        "Prof. Park: Next, the numerical coefficients: 8 / 12. "
        "Both 8 and 12 are divisible by 4. "
        "8 divided by 4 is 2. 12 divided by 4 is 3. "
        "So our fraction has 2 in the numerator and 3 in the denominator.\n"
        "TA Sora: Now the x terms: x^9 on top and x^4 on the bottom. "
        "By the quotient rule: 9 - 4 = 5. Since the larger exponent was on top, x^5 stays in the numerator.\n"
        "Prof. Park: Now the y terms: y^8 on top and y^12 on the bottom! "
        "Where are there more y's? In the denominator! "
        "12 - 8 = 4. So the 4 remaining factors of y belong in the DENOMINATOR: y^4.\n"
        "TA Sora: And finally the z terms: we had z^5 on top and z^0 = 1 on the bottom. "
        "So z^5 stays in the numerator. "
        "Now let's assemble our fraction: "
        "In the numerator: 2 x^5 z^5. "
        "In the denominator: 3 y^4. "
        "Our final answer is: (2x^5 z^5) / (3y^4)!\n"
        "Prof. Park: Sora, how can a student verify their answer on an exam if they have a spare two minutes?\n"
        "TA Sora: Test with friendly numbers! Let x = 1, y = 1, z = 1. "
        "In the original expression: (8 · 1 · 1 · 1) / (12 · 1 · 1 · 1) = 8/12 = 2/3. "
        "In our simplified answer: (2 · 1 · 1) / (3 · 1) = 2/3! "
        "They match perfectly! Every single exponent is positive, the fraction is in lowest terms, and every variable appears exactly once. A masterpiece of algebraic simplification!"
    ),
    10: (
        "Prof. Park: That brings us to the conclusion of Lecture 05! "
        "We have conquered the zero exponent rule, the product rule, and the quotient rule for monomial expressions. "
        "Sora, what can students look forward to in Lecture 06?\n"
        "TA Sora: In Lecture 06, we continue Section 1.2 on workbook pages 10 and 11, tackling Negative Exponents and Power Rules! "
        "We will see what a^(-n) really means—an elevator ticket that moves factors between numerator and denominator—"
        "and how to raise powers to other powers, like (x^a)^b = x^(a·b). "
        "Make sure to practice the exercises on workbook pages 8, 9, and 10 tonight.\n"
        "Prof. Park: Review your properties, keep your work modular and organized on paper, and we will see you all in Lecture 06!"
    )
}
