# -*- coding: utf-8 -*-
"""
unit1_scripts_l01_l03.py
High-volume 20-25 minute broadcast tiki-taka scripts for Lectures 01, 02, and 03.
Prof. Eunju Park & TA Sora.
Target: ~2,350-2,600 words per lecture (~240-290 words per slide).
"""

SCRIPTS_L01 = {
    1: (
        "Prof. Park: Welcome everyone to M090 Introductory Algebra here at Gallatin College Montana State University! "
        "I am Professor Eunju Park, and joining me at the teaching desk is our exceptional graduate teaching assistant, Sora.\n"
        "TA Sora: Hello everyone! Whether you are taking this course right here on our Bozeman campus or tuning in from anywhere across Gallatin County, "
        "we want you to know one fundamental truth right from day one: mathematics is not an inherited talent gene. It is a set of clean, repeatable mental tools. "
        "If you have ever felt math anxiety in your past schooling, or felt that fractions and variables were an incomprehensible mystery, this classroom is your fresh start.\n"
        "Prof. Park: That is so well said, Sora. Math anxiety usually comes from being rushed through mechanical rules without understanding the 'why' behind them. "
        "In M090, our philosophy is entirely different: we build our foundation brick by brick, connecting mathematical operations to concrete physical realities. "
        "Today, we begin Section 1.0 on page 3 of your course workbook, reviewing essential arithmetic tools and setting our expectations for algebraic reasoning.\n"
        "TA Sora: Exactly. Look around our Gallatin Valley—whether someone is measuring timber to frame a house in Belgrade, calculating fuel efficiency driving up to Bridger Bowl, "
        "or monitoring elevation changes on the mountain trails, algebra is the language people use to make sense of numbers in action. "
        "Over the next 45 lectures, we are going to walk through every single workbook example together, step by step, with complete clarity. Let's dive right into our core definitions!"
    ),
    2: (
        "Prof. Park: Let's begin on workbook page 3 with two foundational concepts: variables and constants. "
        "In everyday conversation, when something is 'constant', it never changes. In mathematics, a constant is a fixed number—like 7, -12, or the number of inches in a foot, which is always 12.\n"
        "TA Sora: And in contrast, a variable is a symbol—almost always an English letter like x, y, t, or r—that represents a quantity that can vary or take on different numerical values. "
        "Think of a variable as an empty pocket or an open container waiting for real-world data.\n"
        "Prof. Park: Look at the famous distance formula on our slide: D = r · t. Distance equals rate times time. "
        "Here, all three letters—D, r, and t—are variables. Suppose you are driving west from Bozeman toward Butte along Interstate 90 at a steady cruise control speed of 70 miles per hour. "
        "Your rate r is temporarily fixed at 70. But time t is constantly changing as you travel!\n"
        "TA Sora: Right! After 1 hour, t = 1, so your distance D is 70 times 1, which is 70 miles. "
        "After 2 hours, t = 2, so D = 70 times 2, which gives 140 miles, putting you right past Whitehall. "
        "After 2.5 hours, t = 2.5, so D is 70 times 2.5, which gives 175 miles. "
        "Notice what happened: the formula D = r · t doesn't just describe one single trip; it models every possible road trip on planet Earth. "
        "That is the superpower of algebra: instead of doing individual arithmetic calculations over and over, we write one algebraic relationship that governs all cases."
    ),
    3: (
        "Prof. Park: Now let's establish one of the most critical conceptual boundaries in all of mathematics: the difference between an algebraic expression and an algebraic equation. "
        "Students often mix these two words up, but they belong to entirely different grammatical and logical categories.\n"
        "TA Sora: Yes! Think of an algebraic expression as a grammatical phrase—it is an incomplete thought without a verb. "
        "Examples include 3x + 5, or 2a - 7b, or the fraction x over 4. Notice that there is NO equal sign anywhere in an expression. "
        "Because there is no equal sign, an expression cannot be 'true' or 'false', and you CANNOT 'solve' an expression. "
        "You can only simplify it by combining like terms, or evaluate it by plugging in numbers for the variables.\n"
        "Prof. Park: Exactly. On the other hand, an algebraic equation contains the equal sign, '=', which acts as the verb of a complete mathematical sentence. "
        "For instance, 3x + 5 = 20 is an equation. It asserts a balanced relationship: the quantity on the left scale exactly equals the quantity on the right scale.\n"
        "TA Sora: That equal sign is a sacred boundary. With an equation, our goal is to solve for the unknown variable by performing balanced operations to both sides—adding, subtracting, multiplying, or dividing equally on both sides of the scale. "
        "Here is my golden warning for every exam: You NEVER add 5 to 'both sides' of an expression like 3x + 5, because there is no other side! "
        "An expression is one single object on your desk; an equation is a balanced two-pan balance scale. Respecting the equal sign threshold will save you from dozens of common algebra pitfalls."
    ),
    4: (
        "Prof. Park: Now let's turn to workbook page 4 for Board Work #1: simplifying 1/8 + 1/6 into a single fraction in lowest terms. "
        "Sora, whenever students see fraction addition, what is the instinctive mistake they make?\n"
        "TA Sora: Oh, the classic instinct is to add straight across: 1 + 1 on top is 2, and 8 + 6 on the bottom is 14, giving 2/14. "
        "That is mathematically disastrous! Denominators represent the size of the pieces. If you have an eighth of an inch on a carpentry tape measure and you add a sixth of an inch, "
        "you do not magically end up with fourteenths of an inch. To add fractions, the pieces must be of identical size, which means finding a Least Common Denominator, or LCD.\n"
        "Prof. Park: Exactly. Let's find the LCD of 8 and 6. Multiples of 8 are 8, 16, 24, 32... and multiples of 6 are 6, 12, 18, 24... "
        "The smallest common multiple is 24. While 48 is also a common denominator, choosing the smallest one, 24, keeps our numbers neat and manageable.\n"
        "TA Sora: Now we build equivalent fractions by multiplying by 1 in disguise. For 1/8, we multiply numerator and denominator by 3/3, giving 3/24. "
        "For 1/6, we multiply by 4/4, giving 4/24. Now that both fractions share the common denominator of 24, we simply add the numerators: 3 + 4 = 7. "
        "The denominator stays 24. Our final answer is 7/24. Since 7 is a prime number and does not divide 24, it is fully simplified! "
        "Notice that we never touch the denominator once the sizes match—we only count how many 24th-inch slices we have in total."
    ),
    5: (
        "Prof. Park: Moving to Board Work #2: simplify the product (4)(6/7). Here we have a whole integer multiplied by a fraction. "
        "Sora, how should students visualize whole numbers when working with fractions?\n"
        "TA Sora: Whenever a whole number enters the world of fractions, give it a formal uniform! Any whole integer n can be written as n over 1. "
        "So we rewrite 4 as the fraction 4/1. Our problem becomes (4/1) · (6/7).\n"
        "Prof. Park: Beautiful. And unlike addition, fraction multiplication does NOT require a common denominator. "
        "The rule for multiplication is direct and elegant: multiply straight across the numerators, and multiply straight across the denominators.\n"
        "TA Sora: Exactly. In the numerator, 4 times 6 gives 24. In the denominator, 1 times 7 gives 7. "
        "So our result is 24/7. Now, students often ask: 'Should I convert 24/7 into a mixed number like 3 and 3/7?' "
        "In college algebra, unless a problem specifically asks for a mixed number—like when measuring physical boards in a carpentry shop—we strongly prefer the improper fraction 24/7. "
        "Why? Because in advanced algebra and calculus, mixed numbers create dangerous notation confusion: 3 3/7 looks like 3 multiplied by 3/7! "
        "Improper fractions in lowest terms are clean, unambiguous, and ready for further computation. So 24/7 is our final answer."
    ),
    6: (
        "Prof. Park: Let's examine Board Work #3: 3/5 + 1/4. Here we are adding two fractions whose denominators are 5 and 4. "
        "Notice anything special about the numbers 5 and 4, Sora?\n"
        "TA Sora: Yes! 5 and 4 are coprime, meaning they share no common factors other than 1. 5 is prime, and 4 factors into 2 times 2. "
        "When two denominators share no common factors, their Least Common Denominator is simply their direct product: 5 times 4 = 20.\n"
        "Prof. Park: That makes finding the LCD effortless. Now we convert each fraction into twentieths. "
        "To convert 3/5, we multiply top and bottom by 4/4: (3 · 4) / (5 · 4) = 12/20. "
        "To convert 1/4, we multiply top and bottom by 5/5: (1 · 5) / (4 · 5) = 5/20.\n"
        "TA Sora: Now both fractions are measured in twentieths. We combine the numerators: 12 + 5 = 17, and keep the common denominator 20. "
        "That gives us 17/20. Again, check if 17/20 can be reduced. 17 is a prime number, and it does not divide 20. "
        "So 17/20 is in simplest form. Notice how predictable this process is: find the LCD, scale the numerators, combine, and reduce. "
        "Whether you are working with small integers today or rational polynomial expressions in Unit 4, this exact same four-step rhythm will guide you every single time."
    ),
    7: (
        "Prof. Park: Let's tackle Board Work #4: 3/4 - 5/12. Here we have fraction subtraction. "
        "Notice the relationship between the two denominators, 4 and 12.\n"
        "TA Sora: 12 is a direct multiple of 4, since 4 times 3 equals 12! "
        "That means our Least Common Denominator is simply 12 itself. We do not need to touch the second fraction 5/12 at all.\n"
        "Prof. Park: That is a wonderful time-saver. Students who automatically multiply 4 times 12 get 48, which works, but forces them to simplify much larger numbers at the end. "
        "Instead, we just scale 3/4 by multiplying top and bottom by 3/3: (3 · 3) / (4 · 3) = 9/12.\n"
        "TA Sora: Now we have 9/12 - 5/12. We subtract the numerators: 9 - 5 = 4, over the common denominator 12, giving 4/12. "
        "But wait! Are we done? Absolutely not! Always inspect your final fraction with a critical eye. "
        "Both 4 and 12 are divisible by 4. Dividing the numerator by 4 gives 1, and dividing the denominator by 4 gives 3. "
        "So 4/12 reduces cleanly to 1/3. If you submit 4/12 on an online homework platform or written exam, you will lose points for unsimplified terms. Always finish with 1/3!"
    ),
    8: (
        "Prof. Park: Now look at Board Work #5: (4/7 - 1/7)^2. This problem combines fraction subtraction with an outside exponent of 2. "
        "Sora, order of operations is calling our name here!\n"
        "TA Sora: It certainly is! Under PEMDAS, parentheses come first. We must resolve the operation inside the grouping symbols before applying any external exponent. "
        "Fortunately, inside the parentheses, we have 4/7 - 1/7. Both fractions already share the identical denominator 7!\n"
        "Prof. Park: That makes the inside calculation straightforward: 4/7 - 1/7 = (4 - 1)/7 = 3/7. "
        "So our expression simplifies to (3/7)^2. Now, what does squaring a fraction mean?\n"
        "TA Sora: Squaring a fraction means multiplying that entire fraction by itself: (3/7) · (3/7). "
        "Or, applying the exponent quotient property, the exponent 2 distributes to both the numerator and the denominator: 3^2 / 7^2. "
        "3 squared is 9, and 7 squared is 49. So our final result is 9/49. "
        "Let's point out a major student trap: some students try to square the 4/7 and the 1/7 separately before subtracting. "
        "While algebraically that can lead to complicated formulas, following PEMDAS from the inside out is ten times faster and eliminates errors. Inside first: 3/7, squared gives 9/49!"
    ),
    9: (
        "Prof. Park: Let's look at Board Work #6: (1/9) · (1/5). This is pure fraction multiplication. "
        "Sora, contrast this with addition—why is multiplication so much simpler?\n"
        "TA Sora: Multiplication is the friendliest operation in fraction land because you do NOT need a common denominator! "
        "When you add, you are combining pieces of a pie, so the slices must be equal in size. But when you multiply, you are taking a fraction OF a fraction. "
        "Think of it like taking one-ninth of a one-fifth acre plot in the Gallatin Valley. The new slice is naturally smaller.\n"
        "Prof. Park: Exactly. The rule is simply numerator times numerator, denominator times denominator: "
        "(1 · 1) / (9 · 5) = 1/45.\n"
        "TA Sora: That is as clean as it gets: 1/45. And since 1 is on top, there are no common factors to cancel. "
        "Remember this contrast: addition and subtraction require matching denominators, while multiplication and division never do. "
        "Keeping that distinction crystal clear in your mind eliminates half the stress in algebra arithmetic."
    ),
    10: (
        "Prof. Park: To conclude Lecture 01, we examine Board Work #7: (3/8) ÷ (1/16). "
        "Fraction division! How many 1/16-inch strips can we cut from a piece of wood that is 3/8 inches wide?\n"
        "TA Sora: This is a classic carpentry question! And the universal tool for fraction division is the reciprocal rule: Keep, Change, Flip. "
        "Keep the first fraction: 3/8. "
        "Change division to multiplication: ·. "
        "Flip the second fraction to its reciprocal: 16/1. So our problem becomes (3/8) · (16/1).\n"
        "Prof. Park: Now, you could multiply across: 3 times 16 = 48, and 8 times 1 = 8, giving 48/8, which simplifies to 6. "
        "Or, Sora, show everyone your favorite pre-canceling scalpel!\n"
        "TA Sora: I love pre-canceling! Look at the numerator 16 and the denominator 8. 16 divided by 8 is exactly 2! "
        "So 8 cancels to 1, and 16 cancels to 2. Then we simply multiply: 3 times 2 = 6, divided by 1, which equals 6 whole strips! "
        "Think about that physically: two 1/16ths make 1/8, so six 1/16ths make 3/8. The math matches physical reality perfectly.\n"
        "Prof. Park: Excellent work today, everyone. In Lecture 02, we tackle Board Work #8 through #14, including complex fractions, order of operations, and division by zero. See you all in Lecture 02!"
    )
}

SCRIPTS_L02 = {
    1: (
        "Prof. Park: Welcome back to M090 Introductory Algebra! I am Professor Eunju Park, and with me at the teaching desk is TA Sora. "
        "Today in Lecture 02, we complete our Section 1.0 arithmetic review by conquering Board Work problems #8 through #14 on workbook page 4.\n"
        "TA Sora: Hello everyone! Today's problems are some of the most famous hurdle questions in introductory algebra. "
        "We are tackling complex fractions, pre-canceling with multi-digit products, division by zero, and the notorious PEMDAS order-of-operations traps "
        "that spark endless arguments on social media every single year. "
        "By the time we wrap up today's lecture, you won't just know the answers—you will understand the ironclad logic that governs every single step.\n"
        "Prof. Park: That is right. In Lecture 01, we mastered basic fraction addition, subtraction, multiplication, and division. "
        "Today, we take those foundational skills and apply them to composite expressions, signed powers, and edge cases. "
        "Whether you are heading into business administration, nursing, construction engineering, or environmental science, "
        "these exact arithmetic behaviors will serve as the reliable engine behind every formula you will ever use. "
        "Grab your pencil, open your workbook to page 4, and let's conquer Board Work #8!"
    ),
    2: (
        "Prof. Park: Look at Board Work #8: we have a complex fraction, (2/3) over (4/9). "
        "A fraction stacked inside another fraction can look intimidating at first glance, but what is a fraction bar really, Sora?\n"
        "TA Sora: A fraction bar is simply a division symbol in vertical disguise! "
        "In physical applications—like calculating water flow rates through agricultural irrigation pipes in the Gallatin Valley or determining gear ratios in mechanical equipment—"
        "we frequently encounter ratios of rates. Whenever you see a giant fraction with a fraction on top and a fraction on the bottom, "
        "read it aloud from top to bottom: 'Two-thirds divided by four-ninths'. "
        "That immediately turns it into standard horizontal fraction division: (2/3) ÷ (4/9).\n"
        "Prof. Park: Exactly. And from Board Work #7 in Lecture 01, we already know how to handle fraction division: Keep, Change, Flip. "
        "We keep the numerator fraction 2/3. We change division to multiplication. And we flip 4/9 to its reciprocal, 9/4. "
        "So our expression is rewritten as (2/3) · (9/4).\n"
        "TA Sora: Now let's use our pre-canceling scalpel before multiplying! "
        "Look at 9 in the numerator and 3 in the denominator: 9 divided by 3 leaves 3 on top and 1 on the bottom. "
        "Next, look at 2 in the numerator and 4 in the denominator: 2 divided by 4 simplifies to 1 on top and 2 on the bottom. "
        "Now multiply the remaining simplified factors: (1 · 3) / (1 · 2) = 3/2! "
        "If you multiplied straight across without canceling, you would get 18/12, which also reduces to 3/2. "
        "But pre-canceling keeps the numbers small, prevents arithmetic errors, and saves valuable exam minutes. Our final simplified answer is 3/2!"
    ),
    3: (
        "Prof. Park: Now let's examine Board Work #9: 16 - 3/4. Here we are subtracting a fraction from a whole integer. "
        "Sora, where do students encounter this in everyday Montana life?\n"
        "TA Sora: All the time in residential construction and carpentry! "
        "If you are framing a wall in Belgrade or Bozeman with standard 16-inch stud spacing, and you have to trim a 3/4-inch groove for a plumbing pipe, "
        "you need to know the exact remaining span: 16 inches minus 3/4 of an inch. "
        "To combine a whole integer and a fraction cleanly, we put a uniform on 16 by viewing it as 16/1. "
        "Now we have 16/1 - 3/4. The denominators are 1 and 4, so our Least Common Denominator is 4.\n"
        "Prof. Park: To convert 16/1 into fourths, we multiply numerator and denominator by 4/4: "
        "16 times 4 is 64, so 16 equals 64/4. Think of that in coins: 16 whole dollars is exactly 64 quarters!\n"
        "TA Sora: That is such a vivid mental model! If you have 64 quarters in your pocket and you pay 3 quarters for parking, how many quarters remain? "
        "64 - 3 = 61 quarters, which is 61/4! "
        "Now, 61 is a prime number and has no common factors with 4, so 61/4 is our final improper fraction in lowest terms. "
        "If a carpenter on a job site measured this with a tape measure, they would say 15 and 1/4 inches. "
        "But in college algebra, unless mixed numbers are explicitly asked for, 61/4 is our gold standard because it avoids any notation confusion with multiplication."
    ),
    4: (
        "Prof. Park: Board Work #10 presents a fantastic exercise: simplify (16 · 35) / (28 · 20). "
        "Sora, if a student reaches for a calculator or starts multiplying 16 by 35 by hand on their scratch paper, what would you say to them?\n"
        "TA Sora: Stop right there and put the pencil down! If you compute 16 times 35 by hand, you get 560. "
        "And 28 times 20 also gives 560. Then you have 560/560, which simplifies to 1. "
        "While that produces the right answer here, doing multi-digit multiplication by hand under timed exam conditions is an open invitation for arithmetic errors. "
        "It drains your mental energy and creates stress. Instead, use the factor reduction method—pre-cancel before you multiply!\n"
        "Prof. Park: Let's break down the common factors like a master jeweler inspecting gemstones. "
        "Look at 35 on top and 28 on the bottom. Both are multiples of 7! "
        "35 divided by 7 is 5. 28 divided by 7 is 4. "
        "Now look at 16 on top and 20 on the bottom. Both are divisible by 4! 16 divided by 4 is 4. 20 divided by 4 is 5.\n"
        "TA Sora: Now look at what is left on our paper: on top, we have 4 times 5. On the bottom, we have 4 times 5! "
        "The 4 cancels with 4, and the 5 cancels with 5, leaving exactly 1 over 1, which equals 1. "
        "We solved the entire problem without ever multiplying beyond our single-digit times tables! "
        "When you learn to spot common factors, massive arithmetic calculations suddenly collapse into effortless simplifications."
    ),
    5: (
        "Prof. Park: Now we arrive at Board Work #11 and #12, which compare two foundational fraction scenarios: "
        "Board Work #11 is 16/0, and Board Work #12 is 0/16. "
        "Sora, students frequently confuse which one is zero and which one is undefined. Let's make this unforgettable.\n"
        "TA Sora: Let's start with #12: 0/16. Imagine I bake 0 cookies—a totally empty cookie plate—and I want to share them equally among 16 students in our class. "
        "How many cookies does each student receive? Zero cookies! That makes complete physical sense: 0 divided by 16 equals 0. "
        "Whenever zero is in the numerator (the top), and the denominator is non-zero, the result is always 0.\n"
        "Prof. Park: Beautiful. Now contrast that with #11: 16/0. Zero is in the denominator! "
        "Suppose I have 16 fresh cookies, and I ask: 'How many groups of zero cookies can I hand out to use up all 16 cookies?' "
        "That question makes no sense! No matter how many times you hand out zero cookies, you can never account for 16 cookies.\n"
        "TA Sora: In terms of multiplication, division asks: 'What number k multiplied by the bottom gives the top?' "
        "For 0/16, k · 16 = 0, so k = 0 works. "
        "For 16/0, k · 0 = 16. But any number times 0 is 0! No real number can ever multiply by 0 to yield 16. "
        "Therefore, division by zero is mathematically impossible—it is UNDEFINED. "
        "Think of it geometrically: in Unit 3, when we graph lines, a vertical cliff at Bridger Bowl has a horizontal run of 0. "
        "Rise over run becomes rise over 0, which gives an undefined slope! "
        "Remember my memory trick: 0 on top is 'O-K' (0 is okay, it equals 0). 0 on the bottom is 'N-O' (NO! It is undefined). Never divide by zero!"
    ),
    6: (
        "Prof. Park: Now let's tackle Board Work #13: simplify 24 ÷ 4 · 2. "
        "This is the exact type of arithmetic puzzle that goes viral on the internet and gets thousands of conflicting comments. "
        "Sora, why do people get this wrong?\n"
        "TA Sora: People get it wrong because they memorize the acronym PEMDAS—Parentheses, Exponents, Multiplication, Division, Addition, Subtraction—"
        "and mistakenly believe that because 'M' comes before 'D' in the acronym, multiplication MUST always be done before division! "
        "That is completely false.\n"
        "Prof. Park: Absolutely false. Multiplication and division have EQUAL priority. "
        "They are two sides of the same coin—division is just multiplication by the reciprocal. "
        "In modern computer programming languages like Python, C++, and even in spreadsheet formulas in Excel, "
        "when multiplication and division appear together at the same priority level, they must be evaluated strictly from LEFT TO RIGHT, exactly like reading a sentence in English.\n"
        "TA Sora: Let's follow that rule strictly here: moving from left to right, the first operation we encounter is 24 ÷ 4. "
        "24 divided by 4 is 6. "
        "Now we take that result, 6, and multiply by 2: 6 · 2 = 12! "
        "If someone erroneously did multiplication first, they would do 4 · 2 = 8, and then 24 ÷ 8 = 3. 3 is completely wrong! "
        "The correct, unambiguous mathematical value is 12. Remember: M and D are equal partners, evaluated left to right."
    ),
    7: (
        "Prof. Park: Right on cue, Board Work #14 tests the exact same principle with addition and subtraction: 17 - 5 + 8. "
        "Just like multiplication and division, addition and subtraction share equal priority.\n"
        "TA Sora: Exactly. In PEMDAS, 'A' comes before 'S' only because it is easier to pronounce 'PEMDAS' than 'PEMDSA'! "
        "Addition does NOT outrank subtraction. Subtraction is simply the addition of a negative number. "
        "Think of your personal bank account ledger: if you have 17 dollars, spend 5 dollars on coffee, and then deposit an 8-dollar check, "
        "the bank processes the transactions chronologically from left to right!\n"
        "Prof. Park: Let's read this expression from left to right. The first operation is 17 - 5. "
        "17 minus 5 equals 12. "
        "Then we take that intermediate balance, 12, and add 8: 12 + 8 = 20.\n"
        "TA Sora: Let's see the trap: if a student mistakenly prioritized addition because of the letter 'A', they would calculate 5 + 8 = 13 first. "
        "Then they would do 17 - 13 = 4. Again, 4 is incorrect! "
        "Left to right gives 17 - 5 = 12, plus 8 gives 20. "
        "Keep PEMDAS written in two grouped tiers in your notes: Tier 1 is Parentheses; Tier 2 is Exponents; "
        "Tier 3 is [M & D left-to-right]; Tier 4 is [A & S left-to-right]. That two-tier grouping guarantees 100% accuracy every time."
    ),
    8: (
        "Prof. Park: Now let's explore one of the most critical notation traps in all of algebra: identifying the base of an exponent. "
        "Look at the comparison on our slide: (-3)^2 versus -3^2. "
        "They look almost identical, but their mathematical meanings and numerical values are completely different.\n"
        "TA Sora: In (-3)^2, the parentheses act as a secure, locked container. "
        "The exponent 2 is sitting outside the parentheses, which means the ENTIRE quantity inside—both the negative sign and the 3—is the base! "
        "So (-3)^2 means (-3) multiplied by (-3). And a negative times a negative is a positive: (-3) · (-3) = +9.\n"
        "Prof. Park: Now contrast that with -3^2 without parentheses. "
        "An exponent has an extremely short reach—it attaches ONLY to the immediate symbol directly to its left! "
        "Here, the symbol directly to the left of the exponent 2 is the number 3, NOT the negative sign. "
        "The negative sign is a leading multiplier of negative 1: -3^2 means -(3^2), which is -(3 · 3) = -9!\n"
        "TA Sora: Think of it like this: in (-3)^2, the negative sign is wearing thermal underwear under a heavy snowsuit—it is protected inside. "
        "In -3^2, the negative sign is standing outside in a Montana blizzard, completely unattached to the exponent! "
        "This distinction is crucial when we evaluate physics equations—like kinetic energy E = (1/2)m v^2, where velocity v might be negative, "
        "or temperature models during Bozeman sub-zero winter nights. (+9) vs (-9) can make or break an entire exam problem."
    ),
    9: (
        "Prof. Park: Let's step back and synthesize all 14 Board Work skills we covered across Lectures 01 and 02. "
        "This summary table on slide 9 is your master arithmetic reference for the rest of the semester.\n"
        "TA Sora: Let's run down the checklist: "
        "First, Fraction Addition and Subtraction: always find the LCD first, scale the numerators, combine, and reduce. "
        "Second, Fraction Multiplication: multiply straight across, but ALWAYS look for opportunities to pre-cancel common factors beforehand to keep numbers small. "
        "Third, Fraction Division: Keep the first fraction, Change division to multiplication, Flip the second fraction to its reciprocal, then simplify.\n"
        "Prof. Park: Fourth, Complex Fractions: rewrite the main fraction bar as a horizontal division statement, and apply the reciprocal rule. "
        "Fifth, Whole Numbers with Fractions: write every whole integer n as n/1 to preserve structural alignment. "
        "Sixth, Division by Zero: 0 on top is 0; 0 on the bottom is strictly UNDEFINED.\n"
        "TA Sora: And finally, PEMDAS Equal-Priority Rules: Multiplication and Division are evaluated left to right; Addition and Subtraction are evaluated left to right. "
        "And protect your bases with parentheses! If you master these core arithmetic behaviors, you will never lose silly points on algebra exams."
    ),
    10: (
        "Prof. Park: That brings us to the conclusion of Lecture 02 and the complete wrap-up of Section 1.0! "
        "Sora, what lies ahead as we transition to Section 1.1 on workbook page 6?\n"
        "TA Sora: In Lecture 03, we enter the true realm of algebra: Evaluating Algebraic Expressions! "
        "Instead of being given raw numbers, we will be given algebraic formulas with variables—like the discriminant formula b^2 - 4ac and the quadratic formula expression—"
        "and we will be handed negative integers and fractions to substitute in. "
        "We will teach you my signature 'Empty Pockets' technique using protective parentheses so that you never drop a negative sign again.\n"
        "Prof. Park: Make sure to review your workbook pages 3 and 4 tonight, practice the board work exercises until the steps feel completely natural, "
        "and bring your workbook open to page 6 for Lecture 03. Thank you for your focus and hard work, and we will see you in Lecture 03!"
    )
}

SCRIPTS_L03 = {
    1: (
        "Prof. Park: Welcome to Lecture 03 of M090 Introductory Algebra! I am Professor Eunju Park, and joining me at the teaching desk is TA Sora. "
        "Today, we officially transition from basic arithmetic into Section 1.1 of our course workbook, found on page 6: Evaluating Algebraic Expressions.\n"
        "TA Sora: Hello everyone! Substitution is one of the most powerful and frequent operations you will perform throughout algebra, trigonometry, and calculus. "
        "Whenever a wildlife biologist tracks grizzly bear migration ranges in Yellowstone, an architect calculates roof truss loads against Gallatin winter snow, "
        "or an economist projects small business revenues in downtown Bozeman, they start with an algebraic expression and plug in measured values for the variables. "
        "Today, we are going to master how to evaluate expressions with absolute precision and zero sign errors.\n"
        "Prof. Park: Many students think substitution is simply 'plugging in numbers', but without the proper technique, negative signs and exponents can cause endless confusion. "
        "In fact, historical data from college algebra exams shows that more than 70% of student errors trace back to dropped negative signs during substitution! "
        "That is why today we introduce our Golden Rule of Substitution: Protective Parentheses. Let's look at slide 2 to see how this works!"
    ),
    2: (
        "Prof. Park: Slide 2 presents the Golden Rule of Substitution: Protective Parentheses. "
        "Sora, explain your famous 'Empty Pockets' method that students swear by every semester.\n"
        "TA Sora: I love the Empty Pockets method because it physically prevents mistakes before they can happen! "
        "Here is the rule: Everywhere you see a variable in an expression, do NOT immediately write the number. "
        "Instead, erase the letter and replace it with a set of empty parentheses: ( ). Those are your empty pockets.\n"
        "Prof. Park: Once the empty pockets are written down on your paper, you take the numerical value—especially if it is negative—and gently place it inside the pocket. "
        "For example, if you have x^2 and x = -3, write ( )^2 first, then drop -3 inside: (-3)^2. "
        "As we mastered in Lecture 02, (-3)^2 is positive 9. But if you don't use pockets and write -3^2, your brain or calculator will evaluate it as -9!\n"
        "TA Sora: Exactly! The parentheses protect the negative sign and ensure the exponent applies to the whole number. "
        "Furthermore, if you have a coefficient like 4x and x = 5, replacing x with empty pockets gives 4(5), which clearly means 4 times 5 = 20. "
        "Without parentheses, writing 4 next to 5 looks like the two-digit number 45! "
        "Think of empty pockets as safety goggles in a chemistry lab: you put them on before handling dangerous reagents. "
        "Empty pockets first, then substitute. Keep that habit, and you will achieve 100% accuracy on substitution problems."
    ),
    3: (
        "Prof. Park: Let's put this into practice with Section 1.1 Example 1 from workbook page 6: "
        "Evaluate the rational expression (d^2 - f^2) / (d^2 + f^2) for d = -2 and f = 5. "
        "Notice that d is negative and f is positive, and both appear in the numerator and the denominator. "
        "This rational fraction structure actually appears in physics when analyzing optical interference patterns and relativity!\n"
        "TA Sora: Step 1: Empty pockets! In both top and bottom, we write: [ ( )^2 - ( )^2 ] / [ ( )^2 + ( )^2 ]. "
        "Now we place d = -2 into the first pocket and f = 5 into the second pocket: "
        "[ (-2)^2 - (5)^2 ] / [ (-2)^2 + (5)^2 ]. Look how clean and safe that is!\n"
        "Prof. Park: Now evaluate the powers. In the numerator, (-2)^2 is (-2)(-2) = +4. "
        "Then 5^2 is 25. So the numerator becomes 4 - 25. "
        "In the denominator, (-2)^2 is again +4, and 5^2 is 25, so the denominator becomes 4 + 25.\n"
        "TA Sora: Now perform the addition and subtraction: in the numerator, 4 - 25 = -21. "
        "In the denominator, 4 + 25 = 29. "
        "So our fraction is -21/29. Can we reduce this? 29 is a prime number and does not share any common factors with 21. "
        "We place the negative sign cleanly out in front of the fraction: - 21/29. That is our final, fully simplified answer! "
        "Notice how the empty pockets kept the negative sign attached to 2, so (-2)^2 produced positive 4 without hesitation."
    ),
    4: (
        "Prof. Park: Let's turn up the complexity with Example 2 on page 6: "
        "Evaluate (2x^2 + y^2) / | -10 + z^3 | for x = -1, y = -3, and z = 2. "
        "Here we have multiple variables, negative signs, squares, a cube, and absolute value bars in the denominator!\n"
        "TA Sora: Don't panic—just follow our empty pockets routine! "
        "In the numerator: 2( )^2 + ( )^2. We place x = -1 and y = -3 inside: 2(-1)^2 + (-3)^2. "
        "In the denominator: | -10 + ( )^3 |. We place z = 2 inside: | -10 + (2)^3 |.\n"
        "Prof. Park: Let's simplify the numerator first. By order of operations, exponents come before multiplication. "
        "(-1)^2 is +1, so 2(-1)^2 becomes 2(1) = 2. "
        "(-3)^2 is +9. So the numerator is simply 2 + 9 = 11.\n"
        "TA Sora: Now let's handle the denominator. Inside the absolute value bars, we evaluate the power first: 2^3 = 2 · 2 · 2 = 8. "
        "Now we have | -10 + 8 |. "
        "-10 + 8 equals -2. "
        "Now apply the absolute value bars: the absolute value of -2 represents its physical distance from zero on the number line—"
        "just like the elevation difference between downtown Bozeman at 4,820 feet and Bozeman Pass at 5,712 feet is always a positive distance! "
        "The absolute value of -2 is positive 2! So our denominator is simply 2.\n"
        "Prof. Park: Combining numerator and denominator gives 11/2. "
        "11 is prime, so 11/2 is fully reduced. An improper fraction in lowest terms—clean, exact, and complete!"
    ),
    5: (
        "Prof. Park: Now let's look at Example 3: evaluate the discriminant formula, b^2 - 4ac, for a = 5, b = -6, and c = -3. "
        "Sora, students will see this formula again and again when we solve quadratic equations later in the course.\n"
        "TA Sora: Yes! The discriminant b^2 - 4ac tells us whether a quadratic equation has two real solutions, one solution, or no real solutions. "
        "In physics, when an avalanche mitigation crew at Bridger Bowl launches a safety mortar, the projectile trajectory is a parabola, "
        "and this exact formula reveals whether the mortar will clear the ridge. Evaluating it correctly here builds the foundation for solving equations later. "
        "Let's set up our empty pockets: ( )^2 - 4( )( ). "
        "Dropping our values in: b = -6, a = 5, c = -3 gives: (-6)^2 - 4(5)(-3).\n"
        "Prof. Park: Let's evaluate the first term: (-6)^2. Since -6 is inside parentheses, (-6)(-6) = +36. "
        "Now look at the second part: - 4(5)(-3). Sora, how do you like to count the negative signs here?\n"
        "TA Sora: I always count the negative signs in the multiplication block! "
        "We have subtraction (which acts as a negative) and c = -3. That is TWO negative signs being multiplied together: (-4) · (5) · (-3). "
        "A negative times a negative is a POSITIVE! "
        "4 times 5 is 20, and 20 times 3 is 60. So -4(5)(-3) becomes +60! "
        "Now add them together: 36 + 60 = 96. "
        "The most common mistake on this problem is forgetting that the two negatives create an addition, ending up with 36 - 60 = -24. "
        "Counting your signs carefully guarantees you get the correct answer: 96."
    ),
    6: (
        "Prof. Park: Let's move to Example 4: evaluate the full quadratic formula expression: "
        "[ -b + sqrt(b^2 - 4ac) ] / (2a) for a = 1, b = 7, and c = -6. "
        "This looks like a formidable mountain, but when we break it down into modular steps, it is completely straightforward.\n"
        "TA Sora: Exactly! Let's set up our pockets: "
        "[ -( ) + sqrt( ( )^2 - 4( )( ) ) ] / [ 2( ) ]. "
        "Placing our values in: a = 1, b = 7, c = -6: "
        "[ -(7) + sqrt( (7)^2 - 4(1)(-6) ) ] / [ 2(1) ].\n"
        "Prof. Park: Let's evaluate the pieces systematically. "
        "The leading term -(7) is simply -7. "
        "In the denominator, 2(1) is simply 2. "
        "Now look inside the square root, under the radical: 7^2 is 49. "
        "And -4(1)(-6) has two negatives, which multiply to positive: +24. "
        "So inside the radical, we have 49 + 24 = 73.\n"
        "TA Sora: Putting it all together gives: [ -7 + sqrt(73) ] / 2. "
        "Now we ask: can the square root of 73 be simplified? 73 is a prime number, so it has no perfect square factors like 4, 9, 16, or 25. "
        "And we cannot combine -7 with sqrt(73) because one is a rational integer and the other is an irrational radical. "
        "So [ -7 + sqrt(73) ] / 2 is our exact, final algebraic answer! "
        "In college algebra, unless a decimal approximation is explicitly requested, always leave your answer in exact radical form."
    ),
    7: (
        "Prof. Park: Now let's examine Example 5, which uses the same quadratic formula expression, but with different parameters that allow for complete simplification: "
        "Evaluate [ -b + sqrt(b^2 - 4ac) ] / (2a) for a = 2, b = -10, and c = 8.\n"
        "TA Sora: Notice that b is negative here: b = -10! Watch what happens to the leading term -b: "
        "-(-10). Two negatives side by side become positive 10! That is why empty pockets are life-saving. "
        "In the denominator, 2a becomes 2(2) = 4.\n"
        "Prof. Park: Now let's calculate the radicand, b^2 - 4ac: "
        "(-10)^2 - 4(2)(8). "
        "(-10)^2 is +100. "
        "Then 4 times 2 is 8, and 8 times 8 is 64. So we have 100 - 64 = 36!\n"
        "TA Sora: Look at that: the square root of 36! And 36 is a perfect square: sqrt(36) = 6! "
        "Notice the dramatic difference between Example 4 and Example 5: in Example 4, our discriminant was 73, which is not a perfect square, so we had to leave the radical alone. "
        "Here, 36 is a perfect square, which completely unlocks the radical into the whole number 6! "
        "Now our entire expression collapses into pure arithmetic: "
        "(10 + 6) / 4. "
        "10 + 6 is 16. And 16 divided by 4 equals 4! "
        "Look at how an intimidating multi-layered radical formula simplified down to a single clean integer: 4. "
        "When students follow each rule step by step, mathematics reveals its incredible inner harmony."
    ),
    8: (
        "Prof. Park: Let's discuss a critical topic on slide 8: Calculator Pitfalls versus Paper Algebra. "
        "Many students assume that having a scientific or graphing calculator means they cannot make mistakes. "
        "Sora, why do calculators frequently lead students astray during substitution?\n"
        "TA Sora: A calculator is a literal machine—it executes exact keystrokes without knowing your mathematical intentions! "
        "If you want to calculate (-6)^2 and you type: minus, 6, squared, enter, the calculator follows strict order of operations and computes -(6^2) = -36! "
        "Then you write -36 on your exam, and the entire problem is ruined.\n"
        "Prof. Park: Exactly. To get the correct answer on a calculator, you must explicitly type the parentheses: open parenthesis, negative, 6, close parenthesis, squared. "
        "Furthermore, smartphone calculator apps are especially dangerous: many phone calculators do not distinguish between the negative sign (negation) and the minus key (subtraction), "
        "or they evaluate operations immediately after each keystroke rather than respecting algebraic grouping.\n"
        "TA Sora: Yes! And when evaluating a large fraction like (d^2 - f^2) / (d^2 + f^2), if you type d^2 - f^2 / d^2 + f^2 on a single line, "
        "the calculator will only divide f^2 by d^2 in the middle, completely ruining the formula! "
        "That is why paper algebra is superior: when you write the fraction bar on paper, the horizontal bar naturally groups the entire numerator and the entire denominator. "
        "Always write down your intermediate steps on paper first, and use your calculator solely as a secondary verification tool."
    ),
    9: (
        "Prof. Park: To wrap up Lecture 03, let's review Sora's Substitution Checklist on slide 9. "
        "These four steps will guide you through any evaluation problem in the course.\n"
        "TA Sora: Step 1: Replace every variable with empty parentheses ( ) before writing any numbers. "
        "Step 2: Carefully drop the assigned values into their respective pockets, paying special attention to negative signs. "
        "Step 3: Follow PEMDAS strictly: evaluate inside grouping symbols first, then powers/exponents, then multiplication/division from left to right, and finally addition/subtraction. "
        "Step 4: Check if your final fraction can be reduced, and ensure negative signs are clearly written out front.\n"
        "Prof. Park: And one final word on paper craftsmanship: keep your equal signs neatly aligned down the left margin, and never cram your work into a tiny corner of your notebook. "
        "Giving your algebra room to breathe on paper is the single most effective way to eliminate mental fatigue and catching careless slips before turning in your exam.\n"
        "TA Sora: In Lecture 04, we will take our algebraic skills in a different direction: translating English words and phrases into algebraic expressions on workbook page 7. "
        "We will learn the signal words for addition, subtraction, multiplication, and division, and how to spot order-reversal keywords like 'less than' and 'subtracted from'. "
        "Great work today, everyone, and we will see you in Lecture 04!"
    )
}
